pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import qs.services

/**
 * Curated AI provider connections.
 *
 * Presets describe stable provider-level details only. Model IDs and their
 * capabilities come from live discovery whenever the provider exposes a
 * catalog. The legacy `model` field remains as a compatibility fallback for
 * the existing custom-model form.
 */
Singleton {
    id: root

    readonly property var presets: [
        {
            "id": "ollama",
            "name": "Ollama",
            "icon": "ollama-symbolic",
            "endpoint": "http://127.0.0.1:11434/v1/chat/completions",
            "model": "llama3.2",
            "api_format": "openai",
            "requiresKey": false,
            "keyId": "ollama",
            "keyGetLink": "https://ollama.com/download",
            "description": Translation.tr("Private local models. Installed models are detected automatically."),
            "free": true,
            "local": true,
            "featured": true,
            "catalogKind": "ollama",
            "modelsEndpoint": "http://127.0.0.1:11434/api/tags",
            "authScheme": "none",
        },
        {
            "id": "lmstudio",
            "name": "LM Studio",
            "icon": "neurology",
            "endpoint": "http://127.0.0.1:1234/v1/chat/completions",
            "model": "local-model",
            "api_format": "openai",
            "requiresKey": false,
            "keyId": "lmstudio",
            "keyGetLink": "https://lmstudio.ai",
            "description": Translation.tr("Private local models served by LM Studio's OpenAI-compatible API."),
            "free": true,
            "local": true,
            "featured": true,
            "catalogKind": "openai-compatible",
            "modelsEndpoint": "http://127.0.0.1:1234/v1/models",
            "authScheme": "none",
        },
        {
            "id": "openrouter",
            "name": "OpenRouter",
            "icon": "spark-symbolic",
            "endpoint": "https://openrouter.ai/api/v1/chat/completions",
            "model": "openrouter/free",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "openrouter",
            "keyGetLink": "https://openrouter.ai/settings/keys",
            "description": Translation.tr("A live catalog from many providers, including models that may currently be free."),
            "free": true,
            "local": false,
            "featured": true,
            "catalogKind": "openrouter",
            "modelsEndpoint": "https://openrouter.ai/api/v1/models",
            "publicCatalog": true,
            "authScheme": "bearer",
        },
        {
            "id": "google-gemini",
            "name": "Google Gemini",
            "icon": "google-gemini-symbolic",
            "endpoint": "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
            "model": "gemini-flash-latest",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "gemini",
            "keyGetLink": "https://aistudio.google.com/apikey",
            "description": Translation.tr("Gemini models with live capability and context metadata. A free tier may be available."),
            "free": true,
            "local": false,
            "featured": true,
            "catalogKind": "gemini",
            "modelsEndpoint": "https://generativelanguage.googleapis.com/v1beta/models",
            "catalogApiFormat": "gemini",
            "catalogChatEndpoint": "https://generativelanguage.googleapis.com/v1beta/models/{model}:streamGenerateContent",
            "authScheme": "bearer",
            "catalogAuthScheme": "gemini-query",
        },
        {
            "id": "groq",
            "name": "Groq",
            "icon": "spark-symbolic",
            "endpoint": "https://api.groq.com/openai/v1/chat/completions",
            "model": "llama-3.3-70b-versatile",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "groq",
            "keyGetLink": "https://console.groq.com/keys",
            "description": Translation.tr("Fast hosted inference, speech models and tool-capable models. Free access may be available."),
            "free": true,
            "local": false,
            "featured": true,
            "catalogKind": "openai-compatible",
            "modelsEndpoint": "https://api.groq.com/openai/v1/models",
            "authScheme": "bearer",
        },
        {
            "id": "mistral",
            "name": "Mistral",
            "icon": "mistral-symbolic",
            "endpoint": "https://api.mistral.ai/v1/chat/completions",
            "model": "mistral-small-latest",
            "api_format": "mistral",
            "requiresKey": true,
            "keyId": "mistral",
            "keyGetLink": "https://console.mistral.ai/api-keys",
            "description": Translation.tr("Mistral's live model catalog and experimentation access."),
            "free": true,
            "local": false,
            "catalogKind": "mistral",
            "modelsEndpoint": "https://api.mistral.ai/v1/models",
            "authScheme": "bearer",
        },
        {
            "id": "cerebras",
            "name": "Cerebras",
            "icon": "spark-symbolic",
            "endpoint": "https://api.cerebras.ai/v1/chat/completions",
            "model": "llama-3.3-70b",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "cerebras",
            "keyGetLink": "https://cloud.cerebras.ai",
            "description": Translation.tr("Very fast hosted inference. Free access may be available."),
            "free": true,
            "local": false,
            "catalogKind": "openai-compatible",
            "modelsEndpoint": "https://api.cerebras.ai/v1/models",
            "authScheme": "bearer",
        },
        {
            "id": "anthropic",
            "name": "Anthropic",
            "icon": "anthropic-symbolic",
            "endpoint": "https://api.anthropic.com/v1/messages",
            "model": "claude-sonnet-4-5",
            "api_format": "anthropic",
            "requiresKey": true,
            "keyId": "anthropic",
            "keyGetLink": "https://console.anthropic.com/settings/keys",
            "description": Translation.tr("Claude models discovered from Anthropic's live Models API."),
            "free": false,
            "local": false,
            "catalogKind": "anthropic",
            "modelsEndpoint": "https://api.anthropic.com/v1/models",
            "authScheme": "anthropic",
        },
        {
            "id": "openai",
            "name": "OpenAI",
            "icon": "openai-symbolic",
            "endpoint": "https://api.openai.com/v1/chat/completions",
            "model": "gpt-4.1-mini",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "openai",
            "keyGetLink": "https://platform.openai.com/api-keys",
            "description": Translation.tr("OpenAI models discovered from the live Models API."),
            "free": false,
            "local": false,
            "catalogKind": "openai-compatible",
            "modelsEndpoint": "https://api.openai.com/v1/models",
            "authScheme": "bearer",
        },
        {
            "id": "opencode-zen",
            "name": "OpenCode Zen",
            "icon": "code",
            "endpoint": "https://opencode.ai/zen/v1/chat/completions",
            "model": "north-mini-code-free",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "opencode-zen",
            "keyGetLink": "https://opencode.ai/auth",
            "description": Translation.tr("OpenCode's full live catalog. iNiR selects the correct Responses, Messages, Gemini or Chat Completions route per model."),
            "free": true,
            "local": false,
            "featured": true,
            "catalogKind": "opencode-zen",
            "modelsEndpoint": "https://opencode.ai/zen/v1/models",
            "publicCatalog": true,
            "authScheme": "bearer",
        },
        {
            "id": "opencode-go",
            "name": "OpenCode Go",
            "icon": "code_blocks",
            "endpoint": "https://opencode.ai/zen/go/v1/chat/completions",
            "model": "kimi-k2.7-code",
            "api_format": "openai",
            "requiresKey": true,
            "keyId": "opencode-go",
            "keyGetLink": "https://opencode.ai/auth",
            "description": Translation.tr("OpenCode's lower-cost coding catalog. Available models and the required protocol are discovered automatically."),
            "free": false,
            "local": false,
            "featured": true,
            "catalogKind": "opencode-go",
            "modelsEndpoint": "https://opencode.ai/zen/go/v1/models",
            "publicCatalog": true,
            "authScheme": "bearer",
        },
    ]

    function byId(id) {
        return root.presets.find(p => p.id === id) ?? null;
    }

    function toModelEntry(preset) {
        return {
            "api_format": preset.api_format ?? "openai",
            "name": preset.name,
            "model": preset.model,
            "endpoint": preset.endpoint,
            "description": preset.description ?? "",
            "icon": preset.icon ?? "neurology",
            "requires_key": !!preset.requiresKey,
            "key_id": preset.keyId ?? "",
            "key_get_link": preset.keyGetLink ?? "",
            "provider_id": preset.id ?? "custom",
            "auth_scheme": preset.authScheme ?? "strategy",
        };
    }
}
