# Fish completion for inir CLI
# Install: inir completions fish | source
# Or: inir completions fish > ~/.config/fish/completions/inir.fish

# CLI commands
complete -c inir -n '__fish_use_subcommand' -a install -d 'Install iNiR'
complete -c inir -n '__fish_use_subcommand' -a start -d 'Start the shell'
complete -c inir -n '__fish_use_subcommand' -a stop -d 'Stop the shell'
complete -c inir -n '__fish_use_subcommand' -a run -d 'Run the shell'
complete -c inir -n '__fish_use_subcommand' -a restart -d 'Restart the shell'
complete -c inir -n '__fish_use_subcommand' -a kill -d 'Kill the shell process'
complete -c inir -n '__fish_use_subcommand' -a logs -d 'View runtime logs'
complete -c inir -n '__fish_use_subcommand' -a terminal -d 'Open terminal'
complete -c inir -n '__fish_use_subcommand' -a browser -d 'Open browser'
complete -c inir -n '__fish_use_subcommand' -a close-window -d 'Close focused window'
complete -c inir -n '__fish_use_subcommand' -a ipc -d 'Low-level IPC call'
complete -c inir -n '__fish_use_subcommand' -a settings -d 'Open settings'
complete -c inir -n '__fish_use_subcommand' -a settings-window -d 'Open settings window'
complete -c inir -n '__fish_use_subcommand' -a waffle-settings-window -d 'Open waffle settings'
complete -c inir -n '__fish_use_subcommand' -a repair -d 'Repair shell state'
complete -c inir -n '__fish_use_subcommand' -a path -d 'Show config path'
complete -c inir -n '__fish_use_subcommand' -a test-local -d 'Run local tests'
complete -c inir -n '__fish_use_subcommand' -a setup -d 'Run setup directly'
complete -c inir -n '__fish_use_subcommand' -a service -d 'Manage systemd service'
complete -c inir -n '__fish_use_subcommand' -a doctor -d 'Health checks'
complete -c inir -n '__fish_use_subcommand' -a migrate -d 'Run migrations'
complete -c inir -n '__fish_use_subcommand' -a status -d 'Shell status'
complete -c inir -n '__fish_use_subcommand' -a update -d 'Update shell'
complete -c inir -n '__fish_use_subcommand' -a rollback -d 'Rollback update'
complete -c inir -n '__fish_use_subcommand' -a my-changes -d 'Show local changes'
complete -c inir -n '__fish_use_subcommand' -a uninstall -d 'Uninstall shell'
complete -c inir -n '__fish_use_subcommand' -a config -d 'View/edit config'
complete -c inir -n '__fish_use_subcommand' -a info -d 'System info'
complete -c inir -n '__fish_use_subcommand' -a backup -d 'Create backup'
complete -c inir -n '__fish_use_subcommand' -a version -d 'Show version'
complete -c inir -n '__fish_use_subcommand' -a theme -d 'Theme management'
complete -c inir -n '__fish_use_subcommand' -a help -d 'Show help'
complete -c inir -n '__fish_use_subcommand' -a completions -d 'Generate shell completions'

# IPC targets (auto-generated section)
complete -c inir -n '__fish_use_subcommand' -a ai -d 'AI chat service'
complete -c inir -n '__fish_use_subcommand' -a altSwitcher -d 'Alt+Tab window switcher'
complete -c inir -n '__fish_use_subcommand' -a alt-switcher -d 'Alt+Tab window switcher'
complete -c inir -n '__fish_use_subcommand' -a appCatalog -d 'App catalog service'
complete -c inir -n '__fish_use_subcommand' -a app-catalog -d 'App catalog service'
complete -c inir -n '__fish_use_subcommand' -a audio -d 'Volume and mute control'
complete -c inir -n '__fish_use_subcommand' -a bar -d 'Top bar visibility'
complete -c inir -n '__fish_use_subcommand' -a brightness -d 'Display brightness'
complete -c inir -n '__fish_use_subcommand' -a cheatsheet -d 'Keyboard shortcuts'
complete -c inir -n '__fish_use_subcommand' -a clipboard -d 'Clipboard history'
complete -c inir -n '__fish_use_subcommand' -a cliphistService -d 'Clipboard backend'
complete -c inir -n '__fish_use_subcommand' -a cliphist-service -d 'Clipboard backend'
complete -c inir -n '__fish_use_subcommand' -a closeConfirm -d 'Close confirmation'
complete -c inir -n '__fish_use_subcommand' -a close-confirm -d 'Close confirmation'
complete -c inir -n '__fish_use_subcommand' -a controlPanel -d 'Quick settings'
complete -c inir -n '__fish_use_subcommand' -a control-panel -d 'Quick settings'
complete -c inir -n '__fish_use_subcommand' -a coverflowSelector -d 'Wallpaper coverflow picker'
complete -c inir -n '__fish_use_subcommand' -a coverflow-selector -d 'Wallpaper coverflow picker'
complete -c inir -n '__fish_use_subcommand' -a gamemode -d 'Gaming performance mode'
complete -c inir -n '__fish_use_subcommand' -a globalActions -d 'Command palette'
complete -c inir -n '__fish_use_subcommand' -a global-actions -d 'Command palette'
complete -c inir -n '__fish_use_subcommand' -a lock -d 'Lock screen'
complete -c inir -n '__fish_use_subcommand' -a mediaControls -d 'Media controls'
complete -c inir -n '__fish_use_subcommand' -a media-controls -d 'Media controls'
complete -c inir -n '__fish_use_subcommand' -a minimize -d 'Minimize window'
complete -c inir -n '__fish_use_subcommand' -a mpris -d 'Media player control'
complete -c inir -n '__fish_use_subcommand' -a notifications -d 'Notification management'
complete -c inir -n '__fish_use_subcommand' -a osd -d 'Waffle OSD indicator'
complete -c inir -n '__fish_use_subcommand' -a osdVolume -d 'Volume OSD'
complete -c inir -n '__fish_use_subcommand' -a osd-volume -d 'Volume OSD'
complete -c inir -n '__fish_use_subcommand' -a osk -d 'On-screen keyboard'
complete -c inir -n '__fish_use_subcommand' -a overlay -d 'Central overlay / search'
complete -c inir -n '__fish_use_subcommand' -a overview -d 'Workspace overview'
complete -c inir -n '__fish_use_subcommand' -a orbit -d 'Material session navigator for Niri'
complete -c inir -n '__fish_use_subcommand' -a packageSearch -d 'Package search'
complete -c inir -n '__fish_use_subcommand' -a package-search -d 'Package search'
complete -c inir -n '__fish_use_subcommand' -a panelFamily -d 'Switch panel styles'
complete -c inir -n '__fish_use_subcommand' -a panel-family -d 'Switch panel styles'
complete -c inir -n '__fish_use_subcommand' -a region -d 'Screenshots, OCR, recording'
complete -c inir -n '__fish_use_subcommand' -a search -d 'Waffle start menu'
complete -c inir -n '__fish_use_subcommand' -a session -d 'Power menu'
complete -c inir -n '__fish_use_subcommand' -a shellUpdate -d 'Update checker'
complete -c inir -n '__fish_use_subcommand' -a shell-update -d 'Update checker'
complete -c inir -n '__fish_use_subcommand' -a sidebarLeft -d 'Left sidebar'
complete -c inir -n '__fish_use_subcommand' -a sidebar-left -d 'Left sidebar'
complete -c inir -n '__fish_use_subcommand' -a sidebarRight -d 'Right sidebar'
complete -c inir -n '__fish_use_subcommand' -a sidebar-right -d 'Right sidebar'
complete -c inir -n '__fish_use_subcommand' -a taskview -d 'Family-aware task navigator'
complete -c inir -n '__fish_use_subcommand' -a tiling -d 'Tiling layout'
complete -c inir -n '__fish_use_subcommand' -a voiceSearch -d 'Voice search'
complete -c inir -n '__fish_use_subcommand' -a voice-search -d 'Voice search'
complete -c inir -n '__fish_use_subcommand' -a wactionCenter -d 'Waffle action center'
complete -c inir -n '__fish_use_subcommand' -a waction-center -d 'Waffle action center'
complete -c inir -n '__fish_use_subcommand' -a waffleAltSwitcher -d 'Waffle Alt+Tab'
complete -c inir -n '__fish_use_subcommand' -a waffle-alt-switcher -d 'Waffle Alt+Tab'
complete -c inir -n '__fish_use_subcommand' -a wallpaperSelector -d 'Wallpaper picker'
complete -c inir -n '__fish_use_subcommand' -a wallpaper-selector -d 'Wallpaper picker'
complete -c inir -n '__fish_use_subcommand' -a wbar -d 'Waffle taskbar'
complete -c inir -n '__fish_use_subcommand' -a wnotificationCenter -d 'Waffle notifications'
complete -c inir -n '__fish_use_subcommand' -a wnotification-center -d 'Waffle notifications'
complete -c inir -n '__fish_use_subcommand' -a wwidgets -d 'Waffle widgets'
complete -c inir -n '__fish_use_subcommand' -a ytmusic -d 'YtMusic player control'
complete -c inir -n '__fish_use_subcommand' -a zoom -d 'Screen zoom'

# Subcommand completions: service
complete -c inir -n '__fish_seen_subcommand_from service' -a 'install uninstall enable disable start stop restart status logs'

# Subcommand completions: theme
complete -c inir -n '__fish_seen_subcommand_from theme' -a 'list-targets inspect doctor scaffold apply'

# Subcommand completions: completions
complete -c inir -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish'

# IPC target function completions
complete -c inir -n '__fish_seen_subcommand_from ai' -a 'ensureInitialized diagnose run runGet'
complete -c inir -n '__fish_seen_subcommand_from altSwitcher alt-switcher' -a 'open close toggle next previous'
complete -c inir -n '__fish_seen_subcommand_from appCatalog app-catalog' -a 'refresh search install list'
complete -c inir -n '__fish_seen_subcommand_from audio' -a 'volumeUp volumeDown mute micMute'
complete -c inir -n '__fish_seen_subcommand_from bar' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from brightness' -a 'increment decrement'
complete -c inir -n '__fish_seen_subcommand_from cheatsheet' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from clipboard' -a 'open close toggle'
complete -c inir -n '__fish_seen_subcommand_from cliphistService cliphist-service' -a 'update'
complete -c inir -n '__fish_seen_subcommand_from closeConfirm close-confirm' -a 'trigger triggerWindow close'
complete -c inir -n '__fish_seen_subcommand_from controlPanel control-panel' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from coverflowSelector coverflow-selector' -a 'toggle open close'
complete -c inir -n '__fish_seen_subcommand_from gamemode' -a 'toggle activate deactivate status'
complete -c inir -n '__fish_seen_subcommand_from globalActions global-actions' -a 'run list search open'
complete -c inir -n '__fish_seen_subcommand_from lock' -a 'activate deactivate status focus'
complete -c inir -n '__fish_seen_subcommand_from mediaControls media-controls' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from minimize' -a 'minimize minimizeId restore restoreOriginal'
complete -c inir -n '__fish_seen_subcommand_from mpris' -a 'pauseAll playPause previous next'
complete -c inir -n '__fish_seen_subcommand_from notifications' -a 'test clearAll toggleSilent'
complete -c inir -n '__fish_seen_subcommand_from osd' -a 'trigger'
complete -c inir -n '__fish_seen_subcommand_from osdVolume osd-volume' -a 'trigger hide toggle'
complete -c inir -n '__fish_seen_subcommand_from osk' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from overlay' -a 'toggle'
complete -c inir -n '__fish_seen_subcommand_from overview' -a 'toggle close open toggleReleaseInterrupt clipboardToggle actionOpen'
complete -c inir -n '__fish_seen_subcommand_from orbit' -a 'toggle close open pocket studio find stage orbital next previous status toggleView'
complete -c inir -n '__fish_seen_subcommand_from packageSearch package-search' -a 'search results'
complete -c inir -n '__fish_seen_subcommand_from panelFamily panel-family' -a 'cycle set'
complete -c inir -n '__fish_seen_subcommand_from region' -a 'screenshot search googleLens ocr record recordWithSound'
complete -c inir -n '__fish_seen_subcommand_from search' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from session' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from settings' -a 'open toggle'
complete -c inir -n '__fish_seen_subcommand_from shellUpdate shell-update' -a 'toggle open close check performUpdate dismiss undismiss diagnose'
complete -c inir -n '__fish_seen_subcommand_from sidebarLeft sidebar-left' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from sidebarRight sidebar-right' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from taskview' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from tiling' -a 'toggle open hide cycle showOsd promote'
complete -c inir -n '__fish_seen_subcommand_from voiceSearch voice-search' -a 'start stop toggle'
complete -c inir -n '__fish_seen_subcommand_from wactionCenter waction-center' -a 'toggle'
complete -c inir -n '__fish_seen_subcommand_from waffleAltSwitcher waffle-alt-switcher' -a 'open close toggle next previous'
complete -c inir -n '__fish_seen_subcommand_from wallpaperSelector wallpaper-selector' -a 'toggle open close toggleOnMonitor random'
complete -c inir -n '__fish_seen_subcommand_from wbar' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from wnotificationCenter wnotification-center' -a 'toggle'
complete -c inir -n '__fish_seen_subcommand_from wwidgets' -a 'toggle close open'
complete -c inir -n '__fish_seen_subcommand_from ytmusic' -a 'playPause next previous stop'
complete -c inir -n '__fish_seen_subcommand_from zoom' -a 'zoomIn zoomOut'
