#!/usr/bin/env python3
"""
Generate terminal color configuration files from material_colors.scss
Supports: Kitty, Alacritty, Foot, WezTerm, Ghostty, Konsole
Auto-integrates into existing terminal configs
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from zed.theme_generator import generate_zed_config
from vscode.theme_generator import (
    generate_all_vscode_themes,
    VSCODE_FORKS,
)


def parse_scss_colors(scss_path):
    """Parse material_colors.scss compatibility values."""
    colors = {}
    try:
        with open(scss_path, "r") as f:
            for line in f:
                # Match lines like: $term0: #282828;
                match = re.match(r"\$(\w+):\s*(#[A-Fa-f0-9]{6});", line.strip())
                if match:
                    name, value = match.groups()
                    colors[name] = value
    except FileNotFoundError:
        print(f"Error: Could not find {scss_path}", file=sys.stderr)
        sys.exit(1)
    return colors


def load_json_colors(json_path):
    try:
        with open(json_path, "r") as f:
            data = json.load(f)
            return {k: v for k, v in data.items() if isinstance(v, str)}
    except FileNotFoundError:
        return {}


def load_generator_colors(scss_path, palette_json_path, terminal_json_path):
    colors = parse_scss_colors(scss_path) if scss_path else {}
    palette_colors = load_json_colors(palette_json_path)
    terminal_colors = load_json_colors(terminal_json_path)

    # Explicit contracts should win over SCSS compatibility values.
    colors.update(palette_colors)
    colors.update(terminal_colors)
    return colors


def blend_hex(color1, color2, factor=0.5):
    """Blend two #RRGGBB colors. factor=0 -> color1, factor=1 -> color2."""
    factor = max(0.0, min(1.0, factor))
    c1 = color1.lstrip("#")
    c2 = color2.lstrip("#")
    r1, g1, b1 = int(c1[0:2], 16), int(c1[2:4], 16), int(c1[4:6], 16)
    r2, g2, b2 = int(c2[0:2], 16), int(c2[2:4], 16), int(c2[4:6], 16)
    r = int(r1 + (r2 - r1) * factor)
    g = int(g1 + (g2 - g1) * factor)
    b = int(b1 + (b2 - b1) * factor)
    return f"#{r:02X}{g:02X}{b:02X}"


def ensure_line_in_file(filepath, line_to_add, check_pattern=None, at_top=False):
    """Add a line to a file if it doesn't exist. Creates file if needed."""
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    # Check if file exists and if line already present
    if filepath.exists():
        content = filepath.read_text()
        if check_pattern:
            if re.search(check_pattern, content):
                return False  # Already present
        elif line_to_add in content:
            return False  # Already present
    else:
        content = ""

    # Add line
    if at_top:
        # Add at the beginning of file
        content = line_to_add + "\n" + content
    else:
        # Add at the end
        if content and not content.endswith("\n"):
            content += "\n"
        content += line_to_add + "\n"

    filepath.write_text(content)
    return True  # Added


def generate_kitty_config(colors, output_path):
    """Generate Kitty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

# The basic colors
foreground              {colors.get("term15", "#EBDBB2")}
background              {colors.get("term0", "#282828")}
selection_foreground    {colors.get("term0", "#282828")}
selection_background    {colors.get("term15", "#EBDBB2")}

# Cursor colors
cursor                  {colors.get("term15", "#EBDBB2")}
cursor_text_color       {colors.get("term0", "#282828")}

# URL underline color when hovering with mouse
url_color               {colors.get("term4", "#458588")}

# Kitty window border colors
active_border_color     {colors.get("primary", "#458588")}
inactive_border_color   {colors.get("term8", "#928374")}
bell_border_color       {colors.get("term1", "#CC241D")}

# Tab bar colors
active_tab_foreground   {colors.get("onPrimary", "#FFFFFF")}
active_tab_background   {colors.get("primary", "#458588")}
inactive_tab_foreground {colors.get("term7", "#A89984")}
inactive_tab_background {colors.get("term8", "#928374")}
tab_bar_background      {colors.get("term0", "#282828")}

# The 16 terminal colors

# black
color0 {colors.get("term0", "#282828")}
color8 {colors.get("term8", "#928374")}

# red
color1 {colors.get("term1", "#CC241D")}
color9 {colors.get("term9", "#FB4934")}

# green
color2  {colors.get("term2", "#98971A")}
color10 {colors.get("term10", "#B8BB26")}

# yellow
color3  {colors.get("term3", "#D79921")}
color11 {colors.get("term11", "#FABD2F")}

# blue
color4  {colors.get("term4", "#458588")}
color12 {colors.get("term12", "#83A598")}

# magenta
color5  {colors.get("term5", "#B16286")}
color13 {colors.get("term13", "#D3869B")}

# cyan
color6  {colors.get("term6", "#689D6A")}
color14 {colors.get("term14", "#8EC07C")}

# white
color7  {colors.get("term7", "#A89984")}
color15 {colors.get("term15", "#EBDBB2")}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    # Write config to a secondary file
    theme_conf = os.path.join(os.path.dirname(output_path), "theme.conf")
    with open(theme_conf, "w") as f:
        f.write(config)

    # Use atomic mv for the symlink swap (eliminates race conditions)
    tmp_link = output_path + f".{os.getpid()}.tmp"
    if os.path.lexists(tmp_link):
        os.remove(tmp_link)
    os.symlink("theme.conf", tmp_link)
    os.replace(tmp_link, output_path)

    # Auto-integrate into kitty.conf
    home = os.path.expanduser("~")
    kitty_conf = f"{home}/.config/kitty/kitty.conf"
    if ensure_line_in_file(
        kitty_conf, "include current-theme.conf", r"include\s+current-theme\.conf"
    ):
        print(f"✓ Generated Kitty config and auto-integrated")
    else:
        print(f"✓ Generated Kitty config (already integrated)")

    # Live reload kitty config via SIGUSR1 (updates all windows and tab bar)
    import subprocess

    try:
        subprocess.run(
            ["pkill", "--signal", "SIGUSR1", "-x", "kitty"],
            capture_output=True,
            timeout=2,
        )
        print("  → Live-reloaded Kitty config (SIGUSR1)")
    except Exception:
        pass


def fix_alacritty_import_order(config_path):
    """
    Fix alacritty.toml to use [general] import (Alacritty 0.15+) at the top
    and comment out hardcoded colors. Creates backup before modifying.
    Returns: (modified: bool, message: str)
    """
    try:
        with open(config_path, "r") as f:
            content = f.read()
    except FileNotFoundError:
        return False, "Config file not found"
    except PermissionError:
        return False, "Permission denied"

    import_line = 'import = ["~/.config/alacritty/colors.toml"]'
    bare_import_pat = r"^import\s*=\s*\[.*?colors\.toml.*?\]"
    general_import_pat = r"import\s*=\s*\[.*?colors\.toml.*?\]"
    general_option_pat = r"^(working_directory|live_config_reload|ipc_socket)\s*="

    hoisted_general_lines = []
    hoisted_general_keys = {}

    def _hoist_general_line(stripped_line):
        match = re.match(general_option_pat, stripped_line)
        if not match:
            hoisted_general_lines.append(stripped_line)
            return

        key = match.group(1)
        if key not in hoisted_general_keys:
            hoisted_general_keys[key] = stripped_line
            hoisted_general_lines.append(stripped_line)

    has_hardcoded_colors = bool(
        re.search(r"^\[colors\.(primary|normal|bright)\]", content, re.MULTILINE)
    )

    # Check if [general] with import is already at the top (correct state)
    lines = content.split("\n")
    top_lines = [
        l.strip() for l in lines[:10] if l.strip() and not l.strip().startswith("#")
    ]

    misplaced_general = bool(
        re.search(
            r"^\s*(working_directory|live_config_reload|ipc_socket)\s*=",
            content,
            re.MULTILINE,
        )
    ) and not bool(
        re.search(
            r"^\s*\[general\](?:\n|\r\n)(?:[^\[]*\n|\r\n)*(?:\s*(working_directory|live_config_reload|ipc_socket)\s*=)",
            content,
            re.MULTILINE,
        )
    )

    # Correct state: [general] is first real line, import is second, no hardcoded colors,
    # and no misplaced [general] options elsewhere.
    correct = (
        len(top_lines) >= 2
        and top_lines[0] == "[general]"
        and bool(re.match(general_import_pat, top_lines[1]))
        and not has_hardcoded_colors
        and not misplaced_general
    )
    if correct:
        return False, "Config is already correct"

    # Create backup
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = f"{config_path}.backup_{timestamp}"
    try:
        Path(backup_path).write_text(content)
    except Exception as e:
        return False, f"Failed to create backup: {e}"

    # Build new content: [general] with import at top, then rest of config
    new_lines = [
        "# iNiR wallpaper theming - import must be at top to override colors",
        "[general]",
        import_line,
    ]

    in_general = False
    in_colors_section = False
    added_colors_comment = False

    for line in lines:
        stripped = line.strip()

        # Skip old bare import lines and their iNiR comments
        if re.match(bare_import_pat, stripped):
            continue
        if stripped.startswith("# iNiR wallpaper theming"):
            continue

        # Handle existing [general] section - absorb its non-import content
        if stripped == "[general]":
            in_general = True
            continue
        if in_general:
            if stripped.startswith("[") and stripped != "[general]":
                in_general = False
                # Fall through to process this line normally
            elif re.match(general_import_pat, stripped):
                continue  # Skip - we already added import at top
            elif stripped:
                # Move other [general] settings to top
                _hoist_general_line(stripped)
                continue
            else:
                continue  # Skip empty lines in old [general]

        # Hoist misplaced [general] keys (e.g. accidentally inside [[keyboard.bindings]])
        if re.match(general_option_pat, stripped):
            _hoist_general_line(stripped)
            continue

        # Comment out hardcoded color sections
        if re.match(r"^\[colors\.(primary|normal|bright|cursor|selection)\]", stripped):
            if not added_colors_comment:
                in_colors_section = True
                added_colors_comment = True
                new_lines.append("")
                new_lines.append(
                    "# Color definitions commented out by iNiR wallpaper theming"
                )
                new_lines.append(
                    "# Colors are managed via the import in [general] above"
                )
                new_lines.append("#")
            new_lines.append("# " + line)
            continue

        if in_colors_section:
            if stripped.startswith("[") and not stripped.startswith("[colors"):
                in_colors_section = False
                new_lines.append("")
                new_lines.append(line)
            elif stripped and "=" in stripped:
                new_lines.append("# " + line)
            else:
                new_lines.append("# " + line if stripped else "")
            continue

        new_lines.append(line)

    if hoisted_general_lines:
        new_lines = new_lines[:3] + hoisted_general_lines + [""] + new_lines[3:]

    try:
        Path(config_path).write_text("\n".join(new_lines))
    except Exception as e:
        Path(config_path).write_text(content)
        return False, f"Failed to write config: {e}"

    return True, f"Fixed config (backup: {backup_path})"


def generate_alacritty_config(colors, output_path):
    """Generate Alacritty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[colors.primary]
background = '{colors.get("term0", "#282828")}'
foreground = '{colors.get("term15", "#EBDBB2")}'

[colors.cursor]
text   = '{colors.get("term0", "#282828")}'
cursor = '{colors.get("term15", "#EBDBB2")}'

[colors.selection]
text       = '{colors.get("term0", "#282828")}'
background = '{colors.get("term15", "#EBDBB2")}'

[colors.normal]
black   = '{colors.get("term0", "#282828")}'
red     = '{colors.get("term1", "#CC241D")}'
green   = '{colors.get("term2", "#98971A")}'
yellow  = '{colors.get("term3", "#D79921")}'
blue    = '{colors.get("term4", "#458588")}'
magenta = '{colors.get("term5", "#B16286")}'
cyan    = '{colors.get("term6", "#689D6A")}'
white   = '{colors.get("term7", "#A89984")}'

[colors.bright]
black   = '{colors.get("term8", "#928374")}'
red     = '{colors.get("term9", "#FB4934")}'
green   = '{colors.get("term10", "#B8BB26")}'
yellow  = '{colors.get("term11", "#FABD2F")}'
blue    = '{colors.get("term12", "#83A598")}'
magenta = '{colors.get("term13", "#D3869B")}'
cyan    = '{colors.get("term14", "#8EC07C")}'
white   = '{colors.get("term15", "#EBDBB2")}'
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into alacritty.toml and fix import order
    home = os.path.expanduser("~")
    alacritty_conf = f"{home}/.config/alacritty/alacritty.toml"

    # Fix import order and migrate to [general] import (Alacritty 0.15+)
    if os.path.exists(alacritty_conf):
        modified, message = fix_alacritty_import_order(alacritty_conf)
        if modified:
            print(f"✓ Generated Alacritty config ({message})")
        else:
            print(f"✓ Generated Alacritty config ({message})")
    else:
        # Create new config with [general] import at top
        new_conf = (
            "# iNiR wallpaper theming\n"
            "[general]\n"
            'import = ["~/.config/alacritty/colors.toml"]\n'
        )
        Path(alacritty_conf).parent.mkdir(parents=True, exist_ok=True)
        Path(alacritty_conf).write_text(new_conf)
        print(f"✓ Generated Alacritty config and created new config file")


def generate_foot_config(colors, output_path):
    """Generate Foot terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[colors-dark]
foreground={colors.get("term15", "#EBDBB2")[1:]}
background={colors.get("term0", "#282828")[1:]}

## Normal/regular colors (color palette 0-7)
regular0={colors.get("term0", "#282828")[1:]}  # black
regular1={colors.get("term1", "#CC241D")[1:]}  # red
regular2={colors.get("term2", "#98971A")[1:]}  # green
regular3={colors.get("term3", "#D79921")[1:]}  # yellow
regular4={colors.get("term4", "#458588")[1:]}  # blue
regular5={colors.get("term5", "#B16286")[1:]}  # magenta
regular6={colors.get("term6", "#689D6A")[1:]}  # cyan
regular7={colors.get("term7", "#A89984")[1:]}  # white

## Bright colors (color palette 8-15)
bright0={colors.get("term8", "#928374")[1:]}   # bright black
bright1={colors.get("term9", "#FB4934")[1:]}   # bright red
bright2={colors.get("term10", "#B8BB26")[1:]}  # bright green
bright3={colors.get("term11", "#FABD2F")[1:]}  # bright yellow
bright4={colors.get("term12", "#83A598")[1:]}  # bright blue
bright5={colors.get("term13", "#D3869B")[1:]}  # bright magenta
bright6={colors.get("term14", "#8EC07C")[1:]}  # bright cyan
bright7={colors.get("term15", "#EBDBB2")[1:]}  # bright white

## Cursor and selection colors
selection-foreground={colors.get("term0", "#282828")[1:]}
selection-background={colors.get("term15", "#EBDBB2")[1:]}
jump-labels={colors.get("term0", "#282828")[1:]} {colors.get("term3", "#D79921")[1:]}
urls={colors.get("term4", "#458588")[1:]}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into foot.ini (add at the top to avoid section issues)
    home = os.path.expanduser("~")
    foot_conf = f"{home}/.config/foot/foot.ini"
    if ensure_line_in_file(
        foot_conf,
        "include=~/.config/foot/colors.ini",
        r"include\s*=.*colors\.ini",
        at_top=True,
    ):
        print(f"✓ Generated Foot config and auto-integrated")
    else:
        print(f"✓ Generated Foot config (already integrated)")


def generate_wezterm_config(colors, output_path):
    """Generate WezTerm terminal color config and auto-integrate"""
    config = f"""-- Auto-generated by ii wallpaper theming system
-- Do not edit manually - changes will be overwritten

return {{
  foreground = '{colors.get("term15", "#EBDBB2")}',
  background = '{colors.get("term0", "#282828")}',

  cursor_bg = '{colors.get("term15", "#EBDBB2")}',
  cursor_fg = '{colors.get("term0", "#282828")}',
  cursor_border = '{colors.get("term15", "#EBDBB2")}',

  selection_fg = '{colors.get("term0", "#282828")}',
  selection_bg = '{colors.get("term15", "#EBDBB2")}',

  scrollbar_thumb = '{colors.get("term8", "#928374")}',
  split = '{colors.get("term8", "#928374")}',

  ansi = {{
    '{colors.get("term0", "#282828")}',  -- black
    '{colors.get("term1", "#CC241D")}',  -- red
    '{colors.get("term2", "#98971A")}',  -- green
    '{colors.get("term3", "#D79921")}',  -- yellow
    '{colors.get("term4", "#458588")}',  -- blue
    '{colors.get("term5", "#B16286")}',  -- magenta
    '{colors.get("term6", "#689D6A")}',  -- cyan
    '{colors.get("term7", "#A89984")}',  -- white
  }},

  brights = {{
    '{colors.get("term8", "#928374")}',  -- bright black
    '{colors.get("term9", "#FB4934")}',  -- bright red
    '{colors.get("term10", "#B8BB26")}', -- bright green
    '{colors.get("term11", "#FABD2F")}', -- bright yellow
    '{colors.get("term12", "#83A598")}', -- bright blue
    '{colors.get("term13", "#D3869B")}', -- bright magenta
    '{colors.get("term14", "#8EC07C")}', -- bright cyan
    '{colors.get("term15", "#EBDBB2")}', -- bright white
  }},

  tab_bar = {{
    background = '{colors.get("term0", "#282828")}',
    active_tab = {{
      bg_color = '{colors.get("primary", "#458588")}',
      fg_color = '{colors.get("onPrimary", "#FFFFFF")}',
    }},
    inactive_tab = {{
      bg_color = '{colors.get("term8", "#928374")}',
      fg_color = '{colors.get("term7", "#A89984")}',
    }},
    inactive_tab_hover = {{
      bg_color = '{colors.get("term8", "#928374")}',
      fg_color = '{colors.get("term15", "#EBDBB2")}',
    }},
  }},
}}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into wezterm.lua
    home = os.path.expanduser("~")
    wezterm_conf = f"{home}/.config/wezterm/wezterm.lua"
    integration_code = """local wezterm = require('wezterm')
local config = wezterm.config_builder()
local colors = require('colors')
config.colors = colors
return config
"""

    wezterm_path = Path(wezterm_conf)
    if wezterm_path.exists():
        content = wezterm_path.read_text()
        if "require('colors')" not in content:
            # Add color loading to existing config
            lines = content.split("\n")
            # Find return config line and insert before it
            for i, line in enumerate(lines):
                if "return config" in line or "return {" in line:
                    lines.insert(i, "local colors = require('colors')")
                    lines.insert(i + 1, "config.colors = colors")
                    break
            wezterm_path.write_text("\n".join(lines))
            print(f"✓ Generated WezTerm config and auto-integrated")
        else:
            print(f"✓ Generated WezTerm config (already integrated)")
    else:
        wezterm_path.parent.mkdir(parents=True, exist_ok=True)
        wezterm_path.write_text(integration_code)
        print(f"✓ Generated WezTerm config and auto-integrated (created config)")


def generate_ghostty_config(colors, output_path):
    """Generate Ghostty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

background = {colors.get("term0", "#282828")}
foreground = {colors.get("term15", "#EBDBB2")}

cursor-color = {colors.get("term15", "#EBDBB2")}
cursor-text = {colors.get("term0", "#282828")}

selection-background = {colors.get("term15", "#EBDBB2")}
selection-foreground = {colors.get("term0", "#282828")}

# Black
palette = 0={colors.get("term0", "#282828")}
palette = 8={colors.get("term8", "#928374")}

# Red
palette = 1={colors.get("term1", "#CC241D")}
palette = 9={colors.get("term9", "#FB4934")}

# Green
palette = 2={colors.get("term2", "#98971A")}
palette = 10={colors.get("term10", "#B8BB26")}

# Yellow
palette = 3={colors.get("term3", "#D79921")}
palette = 11={colors.get("term11", "#FABD2F")}

# Blue
palette = 4={colors.get("term4", "#458588")}
palette = 12={colors.get("term12", "#83A598")}

# Magenta
palette = 5={colors.get("term5", "#B16286")}
palette = 13={colors.get("term13", "#D3869B")}

# Cyan
palette = 6={colors.get("term6", "#689D6A")}
palette = 14={colors.get("term14", "#8EC07C")}

# White
palette = 7={colors.get("term7", "#A89984")}
palette = 15={colors.get("term15", "#EBDBB2")}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into ghostty config
    home = os.path.expanduser("~")
    ghostty_conf = f"{home}/.config/ghostty/config"
    if ensure_line_in_file(ghostty_conf, "theme = ii-auto", r"theme\s*=\s*ii-auto"):
        print(f"✓ Generated Ghostty config and auto-integrated")
    else:
        print(f"✓ Generated Ghostty config (already integrated)")


def generate_konsole_config(colors, output_path):
    """Generate Konsole terminal color config"""
    config = f"""[Background]
Color={colors.get("term0", "#282828")[1:]}

[BackgroundIntense]
Color={colors.get("term0", "#282828")[1:]}

[Foreground]
Color={colors.get("term15", "#EBDBB2")[1:]}

[ForegroundIntense]
Color={colors.get("term15", "#EBDBB2")[1:]}

[Color0]
Color={colors.get("term0", "#282828")[1:]}

[Color0Intense]
Color={colors.get("term8", "#928374")[1:]}

[Color1]
Color={colors.get("term1", "#CC241D")[1:]}

[Color1Intense]
Color={colors.get("term9", "#FB4934")[1:]}

[Color2]
Color={colors.get("term2", "#98971A")[1:]}

[Color2Intense]
Color={colors.get("term10", "#B8BB26")[1:]}

[Color3]
Color={colors.get("term3", "#D79921")[1:]}

[Color3Intense]
Color={colors.get("term11", "#FABD2F")[1:]}

[Color4]
Color={colors.get("term4", "#458588")[1:]}

[Color4Intense]
Color={colors.get("term12", "#83A598")[1:]}

[Color5]
Color={colors.get("term5", "#B16286")[1:]}

[Color5Intense]
Color={colors.get("term13", "#D3869B")[1:]}

[Color6]
Color={colors.get("term6", "#689D6A")[1:]}

[Color6Intense]
Color={colors.get("term14", "#8EC07C")[1:]}

[Color7]
Color={colors.get("term7", "#A89984")[1:]}

[Color7Intense]
Color={colors.get("term15", "#EBDBB2")[1:]}

[General]
Description=ii Auto-generated Theme
Opacity=1.0
Wallpaper=
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)
    print(f"✓ Generated Konsole config")


def generate_starship_config(colors, output_path):
    """Generate Starship prompt palette config and auto-integrate"""
    # Starship prompt segments use color names like green/cyan/yellow in the
    # default template. Raw ANSI colors can be too saturated for prompt blocks,
    # so blend them toward semantic Material tokens used by the shell surface.
    starship_red = blend_hex(
        colors.get("term1", "#CC241D"), colors.get("secondary", "#83A598"), 0.45
    )
    starship_green = blend_hex(
        colors.get("term2", "#98971A"), colors.get("primary", "#458588"), 0.45
    )
    starship_yellow = blend_hex(
        colors.get("term3", "#D79921"), colors.get("tertiary", "#D3869B"), 0.45
    )
    starship_blue = blend_hex(
        colors.get("term4", "#458588"), colors.get("primary", "#458588"), 0.45
    )
    starship_magenta = blend_hex(
        colors.get("term5", "#B16286"), colors.get("secondary", "#83A598"), 0.45
    )
    starship_cyan = blend_hex(
        colors.get("term6", "#689D6A"), colors.get("tertiary", "#D3869B"), 0.45
    )

    # Additional muting so Starship blocks don't look neon compared to shell surfaces.
    starship_bg = colors.get("term0", "#282828")
    starship_red = blend_hex(starship_red, starship_bg, 0.20)
    starship_green = blend_hex(starship_green, starship_bg, 0.20)
    starship_yellow = blend_hex(starship_yellow, starship_bg, 0.20)
    starship_blue = blend_hex(starship_blue, starship_bg, 0.20)
    starship_magenta = blend_hex(starship_magenta, starship_bg, 0.20)
    starship_cyan = blend_hex(starship_cyan, starship_bg, 0.20)

    # Starship uses a TOML palette format
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten
# This file provides Material You colors to your Starship prompt

[palettes.ii]
primary = '{colors.get("primary", "#458588")}'
onPrimary = '{colors.get("onPrimary", "#FFFFFF")}'
secondary = '{colors.get("secondary", "#83A598")}'
onSecondary = '{colors.get("onSecondary", "#1D2021")}'
tertiary = '{colors.get("tertiary", "#D3869B")}'
onTertiary = '{colors.get("onTertiary", "#1D2021")}'
surface = '{colors.get("surface", "#1D2021")}'
onSurface = '{colors.get("onSurface", "#EBDBB2")}'
background = '{colors.get("term0", "#282828")}'
foreground = '{colors.get("term15", "#EBDBB2")}'
black = '{colors.get("term0", "#282828")}'
red = '{starship_red}'
green = '{starship_green}'
yellow = '{starship_yellow}'
blue = '{starship_blue}'
magenta = '{starship_magenta}'
cyan = '{starship_cyan}'
white = '{colors.get("term7", "#A89984")}'
bright_black = '{colors.get("term8", "#928374")}'
bright_red = '{colors.get("term9", "#FB4934")}'
bright_green = '{colors.get("term10", "#B8BB26")}'
bright_yellow = '{colors.get("term11", "#FABD2F")}'
bright_blue = '{colors.get("term12", "#83A598")}'
bright_magenta = '{colors.get("term13", "#D3869B")}'
bright_cyan = '{colors.get("term14", "#8EC07C")}'
bright_white = '{colors.get("term15", "#EBDBB2")}'
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into starship.toml
    home = os.path.expanduser("~")
    starship_conf = f"{home}/.config/starship.toml"

    # Check if starship.toml exists
    if os.path.exists(starship_conf):
        content = Path(starship_conf).read_text()

        # Check if palette_name is already set to ii
        if 'palette = "ii"' in content:
            print(f"✓ Generated Starship palette (already using ii palette)")
        else:
            # Add palette directive if not present
            if "palette =" not in content:
                # Add at top of file
                new_content = 'palette = "ii"\n\n' + content
                Path(starship_conf).write_text(new_content)
                content = new_content
                print(f"✓ Generated Starship palette and set as active")
            else:
                print(
                    f"✓ Generated Starship palette (using different palette, change to 'palette = \"ii\"' to use)"
                )

        # Update or append the [palettes.ii] section in starship.toml
        # Starship doesn't support source/include, so palette must be inline
        if "[palettes.ii]" in content:
            # Replace existing palette section with updated colors
            # Find start of [palettes.ii] and end (next section header or EOF)
            pattern = r"\[palettes\.ii\].*?(?=\n\[|\Z)"
            # Extract just the palette block from the generated config
            palette_block = config.strip().split("\n")
            # Skip comment lines at the top, keep from [palettes.ii] onward
            palette_start = next(
                i
                for i, line in enumerate(palette_block)
                if line.startswith("[palettes.ii]")
            )
            palette_content = "\n".join(palette_block[palette_start:])
            new_content = re.sub(pattern, palette_content, content, flags=re.DOTALL)
            if new_content != content:
                Path(starship_conf).write_text(new_content)
                print(f"  → Updated ii palette in starship.toml")
        else:
            with open(starship_conf, "a") as f:
                f.write("\n" + config)
            print(f"  → Appended ii palette to starship.toml")
    else:
        print(
            f"✓ Generated Starship palette (starship.toml not found - create it and add 'palette = \"ii\"')"
        )


def generate_btop_config(colors, output_path):
    """Generate btop theme using Material You design tokens"""

    bg = colors.get("surface", colors.get("background"))
    surface_low = colors.get("surface_container_low")
    surface_std = colors.get("surface_container")
    surface_high = colors.get("surface_container_high")

    on_surface = colors.get("on_surface")
    on_surface_variant = colors.get("on_surface_variant")

    outline = colors.get("outline")
    outline_variant = colors.get("outline_variant")

    primary = colors.get("primary")

    primary_dim = colors.get("primary_fixed_dim")
    secondary_dim = colors.get("secondary_fixed_dim")
    tertiary_dim = colors.get("tertiary_fixed_dim")
    error = colors.get("error")

    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually

theme[main_bg]="{bg}"
theme[main_fg]="{on_surface}"
theme[title]="{on_surface}"
theme[hi_fg]="{primary}"
theme[selected_bg]="{surface_high}"
theme[selected_fg]="{on_surface}"
theme[inactive_fg]="{on_surface_variant}"
theme[graph_text]="{on_surface_variant}"
theme[meter_bg]="{surface_low}"
theme[proc_misc]="{on_surface_variant}"

theme[cpu_box]="{outline_variant}"
theme[mem_box]="{outline_variant}"
theme[net_box]="{outline_variant}"
theme[proc_box]="{outline_variant}"
theme[div_line]="{outline_variant}"

theme[temp_start]="{tertiary_dim}"
theme[temp_mid]="{secondary_dim}"
theme[temp_end]="{error}"

theme[cpu_start]="{tertiary_dim}"
theme[cpu_mid]="{secondary_dim}"
theme[cpu_end]="{error}"

theme[free_start]="{tertiary_dim}"
theme[free_mid]="{tertiary_dim}"
theme[free_end]="{tertiary_dim}"
theme[cached_start]="{primary_dim}"
theme[cached_mid]="{primary_dim}"
theme[cached_end]="{primary_dim}"
theme[available_start]="{secondary_dim}"
theme[available_mid]="{secondary_dim}"
theme[available_end]="{secondary_dim}"
theme[used_start]="{tertiary_dim}"
theme[used_mid]="{secondary_dim}"
theme[used_end]="{error}"

theme[download_start]="{tertiary_dim}"
theme[download_mid]="{tertiary_dim}"
theme[download_end]="{tertiary_dim}"
theme[upload_start]="{secondary_dim}"
theme[upload_mid]="{secondary_dim}"
theme[upload_end]="{secondary_dim}"

theme[process_start]="{primary_dim}"
theme[process_mid]="{primary_dim}"
theme[process_end]="{primary_dim}"
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate: set color_theme in btop.conf
    home = os.path.expanduser("~")
    btop_conf = f"{home}/.config/btop/btop.conf"
    btop_path = Path(btop_conf)
    if btop_path.exists():
        content = btop_path.read_text()
        new_line = 'color_theme = "ii-auto"'
        if re.search(r"^color_theme\s*=", content, re.MULTILINE):
            new_content = re.sub(
                r"^color_theme\s*=.*$", new_line, content, flags=re.MULTILINE
            )
            if new_content != content:
                btop_path.write_text(new_content)
                print(f"\u2713 Generated btop theme and updated btop.conf")
            else:
                print(f"\u2713 Generated btop theme (already using ii-auto)")
        else:
            with open(btop_conf, "a") as f:
                f.write(f"\n{new_line}\n")
            print(f"\u2713 Generated btop theme and added to btop.conf")
    else:
        btop_path.parent.mkdir(parents=True, exist_ok=True)
        btop_path.write_text(f'color_theme = "ii-auto"\n')
        print(f"\u2713 Generated btop theme and created btop.conf")


def generate_omp_config(colors, output_path):
    """Generate oh-my-posh theme using Material You design tokens"""

    surface_container = colors.get("surface_container")
    surface_container_high = colors.get("surface_container_high")

    on_surface = colors.get("on_surface")
    on_surface_variant = colors.get("on_surface_variant")

    primary = colors.get("primary")
    primary_container = colors.get("primary_container")
    on_primary_container = colors.get("on_primary_container")

    error_container = colors.get("error_container")
    on_error_container = colors.get("on_error_container")

    theme = {
        "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
        "version": 4,
        "blocks": [
            {
                "type": "prompt",
                "alignment": "left",
                "segments": [
                    {
                        "type": "executiontime",
                        "style": "plain",
                        "foreground": on_surface_variant,
                        "background": surface_container_high,
                        "template": " {{ .FormattedMs }} ",
                        "properties": {"style": "austin", "threshold": 500},
                    },
                    {
                        "type": "status",
                        "style": "plain",
                        "foreground": on_error_container,
                        "background": error_container,
                        "template": " {{ if gt .Code 0 }}✗ {{ .Code }}{{ end }} ",
                    },
                    {
                        "type": "path",
                        "style": "plain",
                        "foreground": on_surface,
                        "background": surface_container,
                        "template": " {{ .Path }} ",
                        "properties": {"style": "full", "folder_separator_icon": "/"},
                    },
                    {
                        "type": "git",
                        "style": "plain",
                        "foreground": on_primary_container,
                        "background": primary_container,
                        "template": " {{ .HEAD }}{{ if .Working.Changed }} ●{{ end }}{{ if .Staging.Changed }} ✚{{ end }} ",
                        "properties": {"branch_icon": "", "fetch_status": True},
                    },
                ],
            },
            {
                "type": "rprompt",
                "segments": [
                    {
                        "type": "time",
                        "style": "plain",
                        "foreground": on_surface_variant,
                        "template": ' {{ .CurrentDate | date "15:04" }} ',
                    }
                ],
            },
            {
                "type": "prompt",
                "alignment": "left",
                "newline": True,
                "segments": [
                    {
                        "type": "text",
                        "style": "plain",
                        "foreground": primary,
                        "template": "❯ ",
                    }
                ],
            },
        ],
    }

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(theme, f, indent=2)

    print(f"✓ Generated oh-my-posh theme")


def generate_lazygit_config(colors, output_path):
    """Generate lazygit theme config.

    Writes a standalone theme YAML that can be merged into config.yml.
    If config.yml exists, merges the gui.theme section carefully.
    """
    primary = colors.get("primary", "#458588")
    fg = colors.get("term15", "#EBDBB2")
    gray = colors.get("term8", "#928374")
    sel_bg = colors.get("surfaceContainer", colors.get("term8", "#3C3836"))
    red = colors.get("term1", "#CC241D")
    yellow = colors.get("term3", "#D79921")
    green = colors.get("term2", "#98971A")
    blue = colors.get("term4", "#458588")
    magenta = colors.get("term5", "#B16286")

    # The theme block we want inside config.yml
    theme_yaml = f"""    theme:
      activeBorderColor:
        - "{primary}"
        - bold
      inactiveBorderColor:
        - "{gray}"
      optionsTextColor:
        - "{primary}"
      selectedLineBgColor:
        - "{sel_bg}"
      selectedRangeBgColor:
        - "{sel_bg}"
      cherryPickedCommitFgColor:
        - "{primary}"
      cherryPickedCommitBgColor:
        - "{sel_bg}"
      markedBaseCommitFgColor:
        - "{yellow}"
      markedBaseCommitBgColor:
        - "{sel_bg}"
      unstagedChangesColor:
        - "{red}"
      defaultFgColor:
        - "{fg}"
"""

    home = os.path.expanduser("~")
    config_path = f"{home}/.config/lazygit/config.yml"
    config_file = Path(config_path)

    # Also write standalone theme file for reference
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(f"# Auto-generated by ii wallpaper theming system\n")
        f.write(f"# This is the theme section for lazygit config.yml\n")
        f.write(f"gui:\n{theme_yaml}\n")

    if config_file.exists():
        content = config_file.read_text()
        # Check if gui.theme section exists
        if re.search(r"^\s*theme:", content, re.MULTILINE):
            # Replace existing theme block
            # Find "    theme:" and everything indented under it until next key at same/less indent
            pattern = r"(    theme:\n(?:      .*\n)*(?:        .*\n)*)"
            new_content = re.sub(pattern, theme_yaml + "\n", content, count=1)
            if new_content != content:
                config_file.write_text(new_content)
                print(f"\u2713 Generated lazygit theme and updated config.yml")
            else:
                print(f"\u2713 Generated lazygit theme (config.yml unchanged)")
        elif re.search(r"^gui:", content, re.MULTILINE):
            # gui: exists but no theme: — insert theme after gui:
            new_content = re.sub(
                r"^(gui:.*)", r"\1\n" + theme_yaml, content, count=1, flags=re.MULTILINE
            )
            config_file.write_text(new_content)
            print(f"\u2713 Generated lazygit theme and added to gui section")
        else:
            # No gui: section at all — append
            with open(config_path, "a") as f:
                f.write(f"\ngui:\n{theme_yaml}\n")
            print(f"\u2713 Generated lazygit theme and appended gui section")
    else:
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text(f"gui:\n{theme_yaml}\n")
        print(f"\u2713 Generated lazygit config with theme")


def generate_yazi_config(colors, output_path):
    """Generate yazi flavor for ii theming.

    Creates a flavor directory at ~/.config/yazi/flavors/ii-auto.yazi/
    with a flavor.toml that uses the material colors.
    """
    bg = colors.get("term0", "#282828")
    fg = colors.get("term15", "#EBDBB2")
    fg_dim = colors.get("term7", "#A89984")
    gray = colors.get("term8", "#928374")
    primary = colors.get("primary", "#458588")
    sel_bg = colors.get("surfaceContainer", colors.get("term8", "#3C3836"))
    red = colors.get("term1", "#CC241D")
    green = colors.get("term2", "#98971A")
    yellow = colors.get("term3", "#D79921")
    blue = colors.get("term4", "#458588")
    magenta = colors.get("term5", "#B16286")
    cyan = colors.get("term6", "#689D6A")

    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[mgr]
cwd = {{ fg = "{primary}" }}
hovered         = {{ fg = "{bg}", bg = "{primary}" }}
preview_hovered = {{ underline = true }}
find_keyword    = {{ fg = "{yellow}", italic = true }}
find_position   = {{ fg = "{magenta}", bg = "reset", italic = true }}
marker_selected = {{ fg = "{green}", bg = "{green}" }}
marker_copied   = {{ fg = "{yellow}", bg = "{yellow}" }}
marker_cut      = {{ fg = "{red}", bg = "{red}" }}
tab_active      = {{ fg = "{bg}", bg = "{sel_bg}" }}
tab_inactive    = {{ fg = "{fg_dim}", bg = "{sel_bg}" }}
tab_width       = 1
border_symbol   = "\u2502"
border_style    = {{ fg = "{gray}" }}
count_copied    = {{ fg = "{bg}", bg = "{yellow}" }}
count_cut       = {{ fg = "{bg}", bg = "{red}" }}
count_selected  = {{ fg = "{bg}", bg = "{primary}" }}

[mode]
normal_main = {{ fg = "{bg}", bg = "{primary}", bold = true }}
normal_alt  = {{ fg = "{bg}", bg = "{primary}", bold = true }}
select_main = {{ fg = "{bg}", bg = "{green}", bold = true }}
select_alt  = {{ fg = "{bg}", bg = "{green}", bold = true }}
unset_main  = {{ fg = "{bg}", bg = "{magenta}", bold = true }}
unset_alt   = {{ fg = "{bg}", bg = "{magenta}", bold = true }}

[status]
separator_open  = ""
separator_close = ""
separator_style = {{ fg = "{sel_bg}", bg = "{sel_bg}" }}
progress_label  = {{ fg = "{fg}", bold = true }}
progress_normal = {{ fg = "{primary}", bg = "{sel_bg}" }}
progress_error  = {{ fg = "{red}", bg = "{sel_bg}" }}
permissions_t   = {{ fg = "{primary}" }}
permissions_r   = {{ fg = "{yellow}" }}
permissions_w   = {{ fg = "{red}" }}
permissions_x   = {{ fg = "{green}" }}
permissions_s   = {{ fg = "{gray}" }}

[input]
border   = {{ fg = "{primary}" }}
title    = {{}}
value    = {{}}
selected = {{ reversed = true }}

[select]
border   = {{ fg = "{primary}" }}
active   = {{ fg = "{magenta}", bold = true }}
inactive = {{}}

[tasks]
border  = {{ fg = "{primary}" }}
title   = {{}}
hovered = {{ underline = true }}

[which]
mask            = {{ bg = "{sel_bg}" }}
cand            = {{ fg = "{cyan}" }}
rest            = {{ fg = "{gray}" }}
desc            = {{ fg = "{magenta}" }}
separator       = "  "
separator_style = {{ fg = "{gray}" }}

[help]
on      = {{ fg = "{magenta}" }}
run     = {{ fg = "{cyan}" }}
desc    = {{ fg = "{gray}" }}
hovered = {{ bg = "{sel_bg}", bold = true }}
footer  = {{ fg = "{sel_bg}", bg = "{fg_dim}" }}

[filetype]
rules = [
  {{ mime = "image/*", fg = "{magenta}" }},
  {{ mime = "video/*", fg = "{cyan}" }},
  {{ mime = "audio/*", fg = "{cyan}" }},
  {{ mime = "application/zip",             fg = "{red}" }},
  {{ mime = "application/gzip",            fg = "{red}" }},
  {{ mime = "application/x-tar",           fg = "{red}" }},
  {{ mime = "application/x-bzip",          fg = "{red}" }},
  {{ mime = "application/x-bzip2",         fg = "{red}" }},
  {{ mime = "application/x-7z-compressed", fg = "{red}" }},
  {{ mime = "application/x-rar",           fg = "{red}" }},
  {{ name = "*",  fg = "{fg_dim}" }},
  {{ name = "*/", fg = "{primary}" }},
]
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate: set flavor in yazi's theme.toml
    home = os.path.expanduser("~")
    theme_toml = f"{home}/.config/yazi/theme.toml"
    theme_path = Path(theme_toml)

    flavor_line = 'use = "ii-auto"'
    if theme_path.exists():
        content = theme_path.read_text()
        if "[flavor]" in content:
            if re.search(r'^use\s*=\s*"ii-auto"', content, re.MULTILINE):
                print(f"\u2713 Generated yazi flavor (already using ii-auto)")
            elif re.search(r"^use\s*=", content, re.MULTILINE):
                new_content = re.sub(
                    r"^(use\s*=).*$",
                    f'use = "ii-auto"',
                    content,
                    count=1,
                    flags=re.MULTILINE,
                )
                theme_path.write_text(new_content)
                print(f"\u2713 Generated yazi flavor and updated theme.toml")
            else:
                new_content = content.replace("[flavor]", f"[flavor]\n{flavor_line}")
                theme_path.write_text(new_content)
                print(f"\u2713 Generated yazi flavor and added use directive")
        else:
            with open(theme_toml, "a") as f:
                f.write(f"\n[flavor]\n{flavor_line}\n")
            print(f"\u2713 Generated yazi flavor and added [flavor] section")
    else:
        theme_path.parent.mkdir(parents=True, exist_ok=True)
        theme_path.write_text(f"[flavor]\n{flavor_line}\n")
        print(f"\u2713 Generated yazi flavor and created theme.toml")


def generate_fuzzel_config(colors, output_path):
    """Generate Fuzzel launcher theme from material colors"""
    bg = colors.get("background", colors.get("term0", "#282828"))
    fg = colors.get("onBackground", colors.get("term15", "#EBDBB2"))
    surface_var = colors.get("surfaceVariant", colors.get("term8", "#928374"))
    on_surface_var = colors.get("onSurfaceVariant", colors.get("term7", "#A89984"))
    primary = colors.get("primary", "#458588")

    # Strip '#' and add 'ff' alpha
    def hex_alpha(c):
        return c[1:] + "ff" if c.startswith("#") else c + "ff"

    def hex_alpha_dim(c):
        return c[1:] + "dd" if c.startswith("#") else c + "dd"

    config = f"""[colors]
background={hex_alpha(bg)}
text={hex_alpha(fg)}
selection={hex_alpha(surface_var)}
selection-text={hex_alpha(on_surface_var)}
border={hex_alpha_dim(surface_var)}
match={hex_alpha(primary)}
selection-match={hex_alpha(primary)}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)
    print(f"\u2713 Generated Fuzzel theme")


def generate_pywalfox_config(colors, output_path):
    """Generate Pywalfox-compatible JSON from material colors"""
    import json

    bg = colors.get("background", colors.get("term0", "#282828"))
    fg = colors.get("onBackground", colors.get("term15", "#EBDBB2"))
    primary = colors.get("primary", "#458588")

    # Build 16-color palette from term colors
    palette = {}
    for i in range(16):
        palette[f"color{i}"] = colors.get(f"term{i}", "#000000")

    # Read wallpaper path if available
    wallpaper = ""
    wp_path = os.path.expanduser(
        "~/.local/state/quickshell/user/generated/wallpaper/path.txt"
    )
    if os.path.exists(wp_path):
        with open(wp_path) as f:
            wallpaper = f.read().strip()

    pywalfox_data = {
        "wallpaper": wallpaper,
        "alpha": "100",
        "colors": palette,
        "special": {
            "background": bg,
            "foreground": fg,
            "cursor": primary,
        },
    }

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(pywalfox_data, f, indent=2)
    print(f"\u2713 Generated Pywalfox colors")


def main():
    parser = argparse.ArgumentParser(
        description="Generate terminal color configs from material_colors.scss"
    )
    parser.add_argument(
        "--scss",
        type=str,
        default=os.path.expanduser(
            "~/.local/state/quickshell/user/generated/material_colors.scss"
        ),
        help="Path to material_colors.scss file",
    )
    parser.add_argument(
        "--colors",
        type=str,
        default=os.path.expanduser(
            "~/.local/state/quickshell/user/generated/palette.json"
        ),
        help="Path to palette/colors JSON file",
    )
    parser.add_argument(
        "--terminal-json",
        type=str,
        default=os.path.expanduser(
            "~/.local/state/quickshell/user/generated/terminal.json"
        ),
        help="Path to terminal JSON file",
    )
    parser.add_argument(
        "--terminals",
        type=str,
        nargs="+",
        choices=[
            "kitty",
            "alacritty",
            "foot",
            "wezterm",
            "ghostty",
            "konsole",
            "starship",
            "omp",
            "btop",
            "lazygit",
            "yazi",
            "all",
        ],
        default=None,
        help="Which terminals/tools to generate configs for",
    )
    parser.add_argument(
        "--zed",
        action="store_true",
        help="Generate Zed editor theme",
    )
    parser.add_argument(
        "--vscode",
        action="store_true",
        help="Generate VSCode theme (injects into settings.json)",
    )
    parser.add_argument(
        "--vscode-forks",
        type=str,
        nargs="*",
        default=None,
        help=f"Specific VSCode forks to generate for. Options: {', '.join(VSCODE_FORKS.keys())}. Default: all installed",
    )

    args = parser.parse_args()

    # Prefer explicit generated contracts, keep SCSS as compatibility fallback.
    colors = load_generator_colors(args.scss, args.colors, args.terminal_json)

    if not colors:
        print("Error: No colors found in SCSS file", file=sys.stderr)
        sys.exit(1)

    home = os.path.expanduser("~")
    all_terminals = [
        "kitty",
        "alacritty",
        "foot",
        "wezterm",
        "ghostty",
        "konsole",
        "starship",
        "omp",
        "btop",
        "lazygit",
        "yazi",
    ]
    if args.terminals is None:
        terminals = [] if (args.zed or args.vscode) else all_terminals
    else:
        terminals = args.terminals if "all" not in args.terminals else all_terminals

    # Generate configs for requested terminals
    if "kitty" in terminals:
        generate_kitty_config(colors, f"{home}/.config/kitty/current-theme.conf")

    if "alacritty" in terminals:
        generate_alacritty_config(colors, f"{home}/.config/alacritty/colors.toml")

    if "foot" in terminals:
        generate_foot_config(colors, f"{home}/.config/foot/colors.ini")

    if "wezterm" in terminals:
        generate_wezterm_config(colors, f"{home}/.config/wezterm/colors.lua")

    if "ghostty" in terminals:
        generate_ghostty_config(colors, f"{home}/.config/ghostty/themes/ii-auto")

    if "konsole" in terminals:
        generate_konsole_config(
            colors, f"{home}/.local/share/konsole/ii-auto.colorscheme"
        )

    if "starship" in terminals:
        generate_starship_config(colors, f"{home}/.config/starship/ii-palette.toml")

    if "omp" in terminals:
        colors_json_path = args.colors
        terminal_json_path = args.terminal_json
        try:
            with open(colors_json_path, "r") as f:
                m3_colors = json.load(f)
                omp_colors = {**colors, **m3_colors}
                if os.path.exists(terminal_json_path):
                    with open(terminal_json_path, "r") as tf:
                        omp_colors.update(json.load(tf))
                generate_omp_config(
                    omp_colors, f"{home}/.config/oh-my-posh/ii-auto.json"
                )
        except FileNotFoundError:
            print(
                f"Warning: {colors_json_path} not found, oh-my-posh theme may be incomplete"
            )
            generate_omp_config(colors, f"{home}/.config/oh-my-posh/ii-auto.json")

    if "btop" in terminals:
        # btop needs full M3 tokens from palette.json, not just terminal colors
        colors_json_path = args.colors
        try:
            with open(colors_json_path, "r") as f:
                m3_colors = json.load(f)
                # Merge M3 tokens with terminal colors
                btop_colors = {**colors, **m3_colors}
                generate_btop_config(
                    btop_colors, f"{home}/.config/btop/themes/ii-auto.theme"
                )
        except FileNotFoundError:
            print(
                f"Warning: {colors_json_path} not found, btop theme may be incomplete"
            )
            generate_btop_config(colors, f"{home}/.config/btop/themes/ii-auto.theme")

    if "lazygit" in terminals:
        generate_lazygit_config(colors, f"{home}/.config/lazygit/ii-theme.yml")

    if "yazi" in terminals:
        generate_yazi_config(
            colors, f"{home}/.config/yazi/flavors/ii-auto.yazi/flavor.toml"
        )

    if args.zed:
        generate_zed_config(
            colors,
            args.scss,
            f"{home}/.config/zed/themes/ii-theme.json",
            args.colors,
            args.terminal_json,
        )

    if args.vscode:
        # Use the new multi-fork generation that auto-detects all installed forks
        colors_json = args.colors
        # Parse enabled forks from --vscode-forks argument if provided
        forks_to_generate = (
            args.vscode_forks
            if hasattr(args, "vscode_forks") and args.vscode_forks
            else None
        )
        results = generate_all_vscode_themes(colors_json, args.scss, forks_to_generate)
        if not results:
            print("✗ No VSCode forks found or all disabled")


if __name__ == "__main__":
    main()
