#!/usr/bin/env bash
# neovim_themegen.sh — writes the LazyVim plugin spec for yukazakiri/inir.nvim.
# The plugin itself handles all colour fetching, highlights, and live reload.
#
# Usage: neovim_themegen.sh <palette.json> <terminal.json> <plugin_dir>
set -euo pipefail

PALETTE_FILE="${1:?Usage: $0 <palette.json> <terminal.json> <plugin_dir>}"
TERMINAL_FILE="${2:?}"
NEOVIM_PLUGIN_DIR="${3:?}"

NEOVIM_CONFIG_DIR="$(dirname "$(dirname "$NEOVIM_PLUGIN_DIR")")"
NEOVIM_OMARCHY_THEME_FILE="$NEOVIM_PLUGIN_DIR/theme.lua"
NEOVIM_OMARCHY_OVERRIDE_FILE="$NEOVIM_PLUGIN_DIR/zz-inir-omarchy.lua"

# Write file only if changed
write_if_changed() {
  local target="$1" tmp="${1}.tmp"
  cat > "$tmp"
  if [[ -f "$target" ]] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    printf '[neovim_themegen] %s updated\n' "$(basename "$target")"
  fi
}

is_omarchy_theme_link() {
  [[ -L "$NEOVIM_OMARCHY_THEME_FILE" ]] || return 1

  local target
  target="$(readlink "$NEOVIM_OMARCHY_THEME_FILE" 2>/dev/null || true)"
  case "$target" in
    */omarchy/current/theme/neovim.lua) return 0 ;;
    *) return 1 ;;
  esac
}

mkdir -p "$NEOVIM_PLUGIN_DIR"
write_if_changed "$NEOVIM_PLUGIN_DIR/neovim.lua" <<'PLUGEOF'
-- neovim.lua — auto-generated by iNiR. Use 99-inir-user.lua for overrides.
return {
  {
    "yukazakiri/inir.nvim",
    priority = 1000,
    opts = {},
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "inir",
    },
  },
}
PLUGEOF

# Omarchy installs a theme.lua symlink after this file alphabetically. Its
# aether spec would otherwise override iNiR and its LazyReload handler would
# switch back to aether whenever the Omarchy theme changes.
if is_omarchy_theme_link; then
  write_if_changed "$NEOVIM_OMARCHY_OVERRIDE_FILE" <<'OVEREOF'
-- zz-inir-omarchy.lua — auto-generated by iNiR.
-- Keep iNiR authoritative while Neovim wallpaper theming is enabled.
return {
  {
    "bjarneo/aether.nvim",
    enabled = false,
  },
  {
    name = "theme-hotreload",
    dir = vim.fn.stdpath("config"),
    enabled = false,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "inir",
    },
  },
}
OVEREOF
elif [[ -f "$NEOVIM_OMARCHY_OVERRIDE_FILE" ]] && grep -Fq 'auto-generated by iNiR' "$NEOVIM_OMARCHY_OVERRIDE_FILE"; then
  rm -f "$NEOVIM_OMARCHY_OVERRIDE_FILE"
  printf '[neovim_themegen] removed stale: %s\n' "$(basename "$NEOVIM_OMARCHY_OVERRIDE_FILE")"
fi

# Clean up stale files from previous versions
for stale in \
  "$NEOVIM_PLUGIN_DIR/inir-colorscheme.lua" \
  "$NEOVIM_PLUGIN_DIR/inir_theme.lua" \
  "$NEOVIM_CONFIG_DIR/colors/inir.lua"
do
  if [[ -f "$stale" ]]; then
    rm -f "$stale"
    printf '[neovim_themegen] removed stale: %s\n' "$(basename "$stale")"
  fi
done
