# Config file installation for iNiR
# This script is meant to be sourced.

# shellcheck shell=bash

_FILES_STAGE_START=$SECONDS

if ! ${quiet:-false}; then
  printf "${STY_CYAN}[$0]: 3. Copying config files${STY_RST}\n"
fi

#####################################################################################
# Ensure directories exist
#####################################################################################
for dir in "$XDG_BIN_HOME" "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"; do
  if ! test -e "$dir"; then
    v mkdir -p "$dir"
  fi
done

INIR_LAUNCHER_PATH="${XDG_BIN_HOME}/inir"
INIR_APPLICATIONS_DIR="${XDG_DATA_HOME}/applications"
INIR_ICON_DIR="${XDG_DATA_HOME}/icons/hicolor/scalable/apps"

# Create quickshell state directories
v mkdir -p "${XDG_STATE_HOME}/quickshell/user/generated/wallpaper"
v mkdir -p "${XDG_STATE_HOME}/quickshell/user/generated/terminal"
v mkdir -p "${XDG_CACHE_HOME}/quickshell"

# Create initial state files that services expect
# These files prevent FileView warnings on fresh install
touch "${XDG_STATE_HOME}/quickshell/user/gamemode_active" 2>/dev/null || true
touch "${XDG_STATE_HOME}/quickshell/user/notepad.txt" 2>/dev/null || true

# Create empty JSON files for services (only if they don't already exist)
# NOTE: colors.json is NOT created here - it's generated by generate_colors_material.py via switchwall.sh
if [[ ! -f "${XDG_STATE_HOME}/quickshell/user/todo.json" ]]; then
  echo "[]" > "${XDG_STATE_HOME}/quickshell/user/todo.json" 2>/dev/null || true
fi

# Notifications persistence setup
OLD_NOTIF_PATH="${XDG_CACHE_HOME}/quickshell/notifications/notifications.json"
NEW_NOTIF_PATH="${XDG_STATE_HOME}/quickshell/user/notifications.json"

# Migrate from old cache location if exists
if [[ -f "$OLD_NOTIF_PATH" && ! -f "$NEW_NOTIF_PATH" ]]; then
  tui_info "Migrating notifications to persistent storage..."
  mv "$OLD_NOTIF_PATH" "$NEW_NOTIF_PATH"
  rmdir "${XDG_CACHE_HOME}/quickshell/notifications" 2>/dev/null || true
  log_success "Notifications migrated to state directory"
fi

# Create empty notifications file if it doesn't exist (fresh install)
if [[ ! -f "$NEW_NOTIF_PATH" ]]; then
  echo "[]" > "$NEW_NOTIF_PATH"
fi

#####################################################################################
# Determine first run
#####################################################################################
case "${INSTALL_FIRSTRUN}" in
  true) sleep 0 ;;
  *)
    if test -f "${FIRSTRUN_FILE}"; then
      INSTALL_FIRSTRUN=false
    else
      INSTALL_FIRSTRUN=true
    fi
    ;;
esac

#####################################################################################
# Backup existing configs
#####################################################################################
function auto_backup_configs(){
  local backup=false
  case $ask in
    false) [[ ! -d "$BACKUP_DIR" ]] && backup=true ;;
    *)
      if tui_confirm "Backup existing configs to ${BACKUP_DIR}?" "yes"; then
        backup=true
      fi
      ;;
  esac
  if $backup; then
    backup_clashing_targets dots/.config $XDG_CONFIG_HOME "${BACKUP_DIR}/.config"
    [[ -d "${BACKUP_DIR}" ]] && log_success "Backup saved to ${BACKUP_DIR}"
  fi
}

if [[ ! "${SKIP_BACKUP}" == true ]]; then auto_backup_configs; fi

#####################################################################################
# Install Quickshell config (ii)
#####################################################################################
case "${SKIP_QUICKSHELL}" in
  true) sleep 0;;
  *)
    tui_info "Installing Quickshell inir config..."

    # The ii QML code is in the root of this repo, not in dots/
    # We copy it to ~/.config/quickshell/inir/
    II_SOURCE="${REPO_ROOT}"
    II_TARGET="${XDG_CONFIG_HOME}/quickshell/inir"

    v mkdir -p "$II_TARGET"

    # Create backup before update (if this is an update)
    if [[ "${IS_UPDATE}" == "true" ]]; then
      log_info "Creating backup before update..."
      create_update_backup "$II_TARGET" >/dev/null
    fi

    # Generate manifest BEFORE syncing (to know what should exist)
    log_info "Generating file manifest..."
    generate_manifest "$II_SOURCE" "${II_TARGET}/.inir-manifest.new" || return 1

    # Copy all .qml files from root (auto-detect, no manual list needed)
    for qml_file in "${II_SOURCE}"/*.qml; do
      if [[ -f "$qml_file" ]]; then
        install_file "$qml_file" "${II_TARGET}/$(basename "$qml_file")"
      fi
    done

    runtime_root_manifest="${II_SOURCE}/sdata/runtime-root-files.txt"
    if [[ -f "$runtime_root_manifest" ]]; then
      while IFS= read -r runtime_file; do
        [[ -n "$runtime_file" ]] || continue
        if [[ -f "${II_SOURCE}/${runtime_file}" ]]; then
          install_file "${II_SOURCE}/${runtime_file}" "${II_TARGET}/${runtime_file}"
        fi
      done < "$runtime_root_manifest"
    fi

    # Copy runtime payload directories
    runtime_dirs_manifest="${II_SOURCE}/sdata/runtime-payload-dirs.txt"
    if [[ -f "$runtime_dirs_manifest" ]]; then
      while IFS= read -r dir; do
        [[ -n "$dir" ]] || continue
        if [[ -d "${II_SOURCE}/${dir}" ]]; then
          install_dir__sync "${II_SOURCE}/${dir}" "${II_TARGET}/${dir}" || return 1
        fi
      done < "$runtime_dirs_manifest"
    fi

    # Finalize manifest
    mv "${II_TARGET}/.inir-manifest.new" "${II_TARGET}/.inir-manifest"

    # Cleanup orphan files (files that no longer exist in repo)
    if [[ "${IS_UPDATE}" == "true" ]]; then
      log_info "Cleaning up orphan files..."
      cleanup_orphans "$II_TARGET" "${II_TARGET}/.inir-manifest" || return 1
    fi

    # Fix script permissions
    log_info "Setting script permissions..."
    find "$II_TARGET/scripts" \( -name "*.sh" -o -name "*.fish" -o -name "*.py" \) -exec chmod +x {} \; 2>/dev/null || true
    [[ -f "${II_TARGET}/setup" ]] && chmod +x "${II_TARGET}/setup"

    if [[ -f "${REPO_ROOT}/scripts/inir" ]]; then
      if sync_launcher_from_repo >/dev/null; then
        log_success "Launcher installed"
        log_success "Launcher path configured for login and interactive shells"
      else
        log_error "Could not install the inir launcher"
        return 1
      fi
    fi

    local _service_refresh_status=1
    local _service_dir="${XDG_CONFIG_HOME}/systemd/user"
    local _service_asset="${REPO_ROOT}/assets/systemd/inir.service"
    local _service_target="${_service_dir}/inir.service"

    if [[ -f "$_service_asset" ]]; then
      mkdir -p "$_service_dir"

      if inir_user_service_is_masked; then
        systemctl --user unmask inir.service >/dev/null 2>&1 || true
        systemctl --user unmask --runtime inir.service >/dev/null 2>&1 || true
        rm -f "$_service_target"
      fi

      if sync_user_inir_service_from_repo_if_present; then
        _service_refresh_status=0
        log_success "User inir.service refreshed"
      fi
    fi

    if [[ -f "$_service_target" ]]; then
      # Wire to compositor-specific wants so inir only starts under the correct
      # compositor — NOT under KDE/GNOME/etc.  Never fall back to
      # graphical-session.target: that target is active in ANY desktop session.
      local _comp_target=""
      if systemctl --user cat niri.service &>/dev/null; then
        _comp_target="niri.service"
      fi

      if [[ -n "$_comp_target" ]]; then
        local _wants_dir="${XDG_CONFIG_HOME}/systemd/user/${_comp_target}.wants"
        if mkdir -p "$_wants_dir" \
            && ln -sf "${XDG_CONFIG_HOME}/systemd/user/inir.service" "$_wants_dir/inir.service" \
            && systemctl --user daemon-reload >/dev/null 2>&1 \
            && [[ -e "$_wants_dir/inir.service" || -L "$_wants_dir/inir.service" ]]; then
          log_success "User inir.service enabled (wired to ${_comp_target})"
        else
          log_warning "Could not wire inir.service to ${_comp_target} — run 'inir service enable'"
        fi
      else
        log_warning "niri.service not detected"
        log_warning "inir.service not enabled — start Niri as a managed session and run 'inir service enable'"
      fi
    fi

    if [[ -f "${REPO_ROOT}/assets/icons/desktop-symbolic.svg" ]]; then
      install_file "${REPO_ROOT}/assets/icons/desktop-symbolic.svg" "${INIR_ICON_DIR}/inir.svg"
      log_success "Launcher icon installed"
    fi

    if [[ -f "${REPO_ROOT}/assets/applications/inir.desktop" ]]; then
      INIR_DESKTOP_TMP="${XDG_CACHE_HOME}/inir.desktop.$$"
      sed "s|^Exec=.*|Exec=${INIR_LAUNCHER_PATH//&/\\&} service restart|" "${REPO_ROOT}/assets/applications/inir.desktop" > "${INIR_DESKTOP_TMP}"
      install_file "${INIR_DESKTOP_TMP}" "${INIR_APPLICATIONS_DIR}/inir.desktop"
      rm -f "${INIR_DESKTOP_TMP}"
      log_success "Shell desktop entry installed"
    fi

    if [[ -f "${REPO_ROOT}/assets/applications/inir-settings.desktop" ]]; then
      INIR_SETTINGS_DESKTOP_TMP="${XDG_CACHE_HOME}/inir-settings.desktop.$$"
      sed "s|^Exec=.*|Exec=${INIR_LAUNCHER_PATH//&/\\&} settings|" "${REPO_ROOT}/assets/applications/inir-settings.desktop" > "${INIR_SETTINGS_DESKTOP_TMP}"
      install_file "${INIR_SETTINGS_DESKTOP_TMP}" "${INIR_APPLICATIONS_DIR}/inir-settings.desktop"
      rm -f "${INIR_SETTINGS_DESKTOP_TMP}"
      log_success "Settings desktop entry installed"
    fi

    log_success "Quickshell inir config installed"

    # Install Python packages now that requirements.txt is in place
    showfun install-python-packages
    v install-python-packages
    showfun ensure-ytmusic-js-runtime
    v ensure-ytmusic-js-runtime

    # Verify installation (only on updates, not fresh install)
    if [[ "${IS_UPDATE}" == "true" && "${SKIP_VERIFICATION}" != "true" ]]; then
      log_info "Verifying installation..."
      if ! verify_qs_loads 8; then
        log_error "Verification failed!"
        echo ""
        log_warning "Update may have issues — run './setup doctor' or './setup restore' to rollback"
        echo ""
      else
        log_success "Verification passed"
      fi
    fi
    ;;
esac

#####################################################################################
# Install config files from dots/
#####################################################################################
tui_info "Installing config files..."

# Niri config
case "${SKIP_NIRI}" in
  true) sleep 0;;
  *)
    NIRI_CONFIG="${XDG_CONFIG_HOME}/niri/config.kdl"

    # On updates, preserve the user's config and only patch launcher/theme bits.
    # On first run, always install iNiR defaults (backup_clashing_targets already
    # saved the pre-existing config to the backup dir).
    if [[ "${INSTALL_FIRSTRUN}" == true ]]; then
      if [[ -d "defaults/niri" ]]; then
        install_dir__sync "defaults/niri" "${XDG_CONFIG_HOME}/niri"
        log_success "Niri config installed (defaults)"
      elif [[ -d "dots/.config/niri" ]]; then
        install_dir__sync "dots/.config/niri" "${XDG_CONFIG_HOME}/niri"
        log_success "Niri config installed (dots)"
      fi
    elif [[ -f "$NIRI_CONFIG" ]]; then
      log_success "Preserving existing Niri config"
    elif [[ -d "defaults/niri" ]]; then
      install_dir__sync "defaults/niri" "${XDG_CONFIG_HOME}/niri"
      log_success "Niri config installed (defaults)"
    elif [[ -d "dots/.config/niri" ]]; then
      install_dir__sync "dots/.config/niri" "${XDG_CONFIG_HOME}/niri"
      log_success "Niri config installed (dots)"
    fi

    # Patch config.kdl: detect polkit agent
    NIRI_CFG="${XDG_CONFIG_HOME}/niri/config.kdl"
    NIRI_ENV_CFG="${XDG_CONFIG_HOME}/niri/config.d/40-environment.kdl"
    NIRI_STARTUP_CFG="${XDG_CONFIG_HOME}/niri/config.d/50-startup.kdl"
    NIRI_BINDS_CFG="${XDG_CONFIG_HOME}/niri/config.d/70-binds.kdl"
    NIRI_ENV_TARGET="${NIRI_CFG}"
    NIRI_STARTUP_TARGET="${NIRI_CFG}"
    NIRI_BINDS_TARGET="${NIRI_CFG}"

    [[ -f "$NIRI_ENV_CFG" ]] && NIRI_ENV_TARGET="$NIRI_ENV_CFG"
    [[ -f "$NIRI_STARTUP_CFG" ]] && NIRI_STARTUP_TARGET="$NIRI_STARTUP_CFG"
    [[ -f "$NIRI_BINDS_CFG" ]] && NIRI_BINDS_TARGET="$NIRI_BINDS_CFG"

    if [[ -f "$NIRI_CFG" ]]; then
      POLKIT_AGENT="$(get-polkit-agent)"
      if [[ -n "$POLKIT_AGENT" ]]; then
        sed -i "s|spawn-at-startup \"/usr/lib/mate-polkit/polkit-mate-authentication-agent-1\"|spawn-at-startup \"${POLKIT_AGENT}\"|" "$NIRI_STARTUP_TARGET"
        log_success "Polkit agent: $(basename "$(dirname "$POLKIT_AGENT")")/$(basename "$POLKIT_AGENT")"
      else
        log_warning "No polkit agent found — sudo dialogs may not work"
      fi

      # Patch config.kdl: detect QT platform theme
      # plasma-integration provides the "kde" QPA platform theme plugin which reads
      # colors from kdeglobals. Without it, Qt apps can't use KDE color schemes.
      # We check for plasma-integration (not plasma-desktop) because it can be
      # installed standalone for KDE theming without the full Plasma desktop.
      if pacman -Q plasma-integration &>/dev/null 2>&1 || \
         dpkg -l plasma-integration 2>/dev/null | grep -q '^ii' || \
         rpm -q plasma-integration &>/dev/null 2>&1; then
        : # plasma-integration installed — keep "kde" platform theme (reads kdeglobals)
        log_success "Qt theme: kde (plasma-integration detected)"
      else
        # No plasma-integration: fall back to qt6ct
        # NOTE: This is suboptimal — Darkly style won't read kdeglobals colors properly.
        # The user should install plasma-integration for correct Material You Qt theming.
        sed -i 's/QT_QPA_PLATFORMTHEME "kde"/QT_QPA_PLATFORMTHEME "qt6ct"/' "$NIRI_ENV_TARGET"
        log_warning "Qt theme: qt6ct (plasma-integration not found — install it for proper Qt theming)"
      fi

      if niri_can_resolve_launcher_dir "$XDG_BIN_HOME"; then
        sed -i \
          -e 's|spawn "bash" "-lc" "exec \"\$(inir path)/scripts/launch-terminal.sh\""|spawn "inir" "terminal"|' \
          -e 's|spawn "bash" "-lc" "exec \"\$(inir path)/scripts/close-window.sh\""|spawn "inir" "close-window"|' \
          -e 's|spawn "[^"]*/inir" "|spawn "inir" "|g' \
          "$NIRI_BINDS_TARGET"
      else
        log_warning "Niri is still running without ${XDG_BIN_HOME} in PATH — preserving existing launcher paths until the next session"
      fi
    fi
    ;;
esac

# Theming templates — defaults/ is the primary source (kept in sync with dots/)
if [[ -d "defaults/matugen" ]]; then
  install_dir__sync "defaults/matugen" "${XDG_CONFIG_HOME}/matugen"
  log_success "Theming templates installed (defaults)"
elif [[ -d "dots/.config/matugen" ]]; then
  install_dir__sync "dots/.config/matugen" "${XDG_CONFIG_HOME}/matugen"
  log_success "Theming templates installed (dots)"
fi

# ii-pixel-sddm theme (login screen matching ii lockscreen aesthetic)
# This MUST run AFTER theming templates are deployed above, because the distributed
# config includes the SDDM sync post_hook template.
if command -v sddm &>/dev/null; then
  if [[ "${INSTALL_FIRSTRUN}" == true ]]; then
    if [[ "${ask}" == "true" ]]; then
      tui_info "Recommended: install ii-pixel-sddm login theme (matches iNiR lockscreen)."
      if tui_confirm "Install ii-pixel-sddm now?" "yes"; then
        extras_install_sddm_theme "yes"
      else
        log_info "Skipping ii-pixel-sddm setup"
      fi
    else
      # Non-interactive: auto-install SDDM theme
      extras_install_sddm_theme "yes"
    fi
  fi
fi

# Fuzzel (launcher)
if [[ -d "dots/.config/fuzzel" ]]; then
  install_dir__sync "dots/.config/fuzzel" "${XDG_CONFIG_HOME}/fuzzel"
  log_success "Fuzzel config installed"
fi

# Starship (prompt)
if [[ -f "defaults/starship/starship.toml" ]]; then
  install_file__auto_backup "defaults/starship/starship.toml" "${XDG_CONFIG_HOME}/starship.toml"
  log_success "Starship config installed"
fi

# Fish shell config (starship init, terminal sequences, aliases)
if [[ -d "dots/.config/fish" ]]; then
  # Install config.fish and auto-Niri.fish (first run: overwrite, update: preserve)
  for fish_file in config.fish auto-Niri.fish; do
    if [[ -f "dots/.config/fish/${fish_file}" ]]; then
      install_file__auto_backup "dots/.config/fish/${fish_file}" "${XDG_CONFIG_HOME}/fish/${fish_file}"
    fi
  done
  log_success "Fish shell config installed"

  # Set Fish as default shell if requested
  if [[ "${INIR_SET_DEFAULT_SHELL:-}" == "true" ]]; then
    if command -v chsh &>/dev/null; then
      local fish_path
      fish_path=$(command -v fish 2>/dev/null)
      if [[ -n "$fish_path" ]] && [[ -x "$fish_path" ]]; then
        if chsh -s "$fish_path" 2>/dev/null; then
          log_success "Default shell set to Fish ($fish_path)"
        else
          log_warning "Could not set default shell (may require password)"
        fi
      else
        log_warning "Fish shell not found in PATH"
      fi
    else
      log_warning "chsh not available - cannot set default shell"
    fi
  fi
fi

# Foot terminal config
if [[ -f "dots/.config/foot/foot.ini" ]]; then
  install_file__auto_backup "dots/.config/foot/foot.ini" "${XDG_CONFIG_HOME}/foot/foot.ini"
  log_success "Foot terminal config installed"
fi

# Kitty terminal config
if [[ -f "dots/.config/kitty/kitty.conf" ]]; then
  install_file__auto_backup "dots/.config/kitty/kitty.conf" "${XDG_CONFIG_HOME}/kitty/kitty.conf"
  log_success "Kitty terminal config installed"
fi

# Alacritty: patch legacy fields that cause parse errors on Alacritty ≥0.14
# CachyOS and other distros ship default configs with deprecated top-level fields
# like live_config_reload that were moved under [general] in 0.14+.
_alacritty_conf="${XDG_CONFIG_HOME}/alacritty/alacritty.toml"
if [[ -f "$_alacritty_conf" ]]; then
  if grep -qE '^live_config_reload\s*=' "$_alacritty_conf" 2>/dev/null; then
    sed -i '/^live_config_reload\s*=/d' "$_alacritty_conf"
    log_success "Alacritty: removed deprecated live_config_reload (moved to [general] in 0.14+)"
  fi
fi

# Konsole config (if installed)
if command -v konsole &>/dev/null; then
  if [[ -f "dots/.config/konsolerc" ]]; then
    install_file__auto_backup "dots/.config/konsolerc" "${XDG_CONFIG_HOME}/konsolerc"
  fi
  if [[ -f "dots/.local/share/konsole/Profile 1.profile" ]]; then
    mkdir -p "${XDG_DATA_HOME}/konsole"
    install_file "dots/.local/share/konsole/Profile 1.profile" "${XDG_DATA_HOME}/konsole/Profile 1.profile"
  fi
  log_success "Konsole config installed"
fi

# Electron app Wayland flags (Chrome, VS Code)
for flagfile in chrome-flags.conf code-flags.conf; do
  if [[ -f "dots/.config/${flagfile}" ]]; then
    install_file__auto_backup "dots/.config/${flagfile}" "${XDG_CONFIG_HOME}/${flagfile}"
  fi
done

# Darkly Qt style config
if [[ -f "dots/.config/darklyrc" ]]; then
  darkly_target="${XDG_CONFIG_HOME}/darklyrc"
  if [[ ! -f "$darkly_target" ]]; then
    install_file "dots/.config/darklyrc" "$darkly_target"
  else
    # Keep user Darkly preferences intact. Newer Dolphin versions ask the
    # QStyle to draw FrameFocusRect for focused items, and current Darkly draws
    # that as an extra underline. Disable only that one style feature.
    python3 - "$darkly_target" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
text = path.read_text()
section = re.search(r'(?ms)^\[Style\]\s*$.*?(?=^\[|\Z)', text)

if section:
    block = section.group(0)
    if re.search(r'(?m)^ViewDrawFocusIndicator=', block):
        updated = re.sub(
            r'(?m)^ViewDrawFocusIndicator=.*$',
            'ViewDrawFocusIndicator=false',
            block,
            count=1,
        )
    else:
        trailing = re.search(r'(?:\n[ \t]*)*\Z', block).group(0)
        body = block[:-len(trailing)] if trailing else block
        updated = body + ('' if body.endswith('\n') else '\n') \
            + 'ViewDrawFocusIndicator=false' + (trailing or '\n')
    text = text[:section.start()] + updated + text[section.end():]
else:
    if text and not text.endswith('\n'):
        text += '\n'
    text += '\n[Style]\nViewDrawFocusIndicator=false\n'

path.write_text(text)
PY
  fi
fi

# MPV config
if [[ -f "dots/.config/mpv/mpv.conf" ]]; then
  install_file__auto_backup "dots/.config/mpv/mpv.conf" "${XDG_CONFIG_HOME}/mpv/mpv.conf"
fi

# GTK settings
for gtkver in gtk-3.0 gtk-4.0; do
  if [[ -d "dots/.config/${gtkver}" ]]; then
    install_dir "dots/.config/${gtkver}" "${XDG_CONFIG_HOME}/${gtkver}"
  fi
done

# KDE settings (for Qt apps like Dolphin, Kate, etc.)
# These are controlled by iNiR for theming - always overwrite
if [[ -f "defaults/kde/kdeglobals" ]]; then
  install_file "defaults/kde/kdeglobals" "${XDG_CONFIG_HOME}/kdeglobals"
elif [[ -f "dots/.config/kdeglobals" ]]; then
  install_file "dots/.config/kdeglobals" "${XDG_CONFIG_HOME}/kdeglobals"
fi

# Dolphin config — only if dolphin is installed (nautilus is now the default file manager)
if command -v dolphin &>/dev/null; then
  if [[ -f "defaults/kde/dolphinrc" ]]; then
    install_file "defaults/kde/dolphinrc" "${XDG_CONFIG_HOME}/dolphinrc"
  elif [[ -f "dots/.config/dolphinrc" ]]; then
    install_file "dots/.config/dolphinrc" "${XDG_CONFIG_HOME}/dolphinrc"
  fi

  # KDE service menu (enables "Open terminal here" in Dolphin right-click)
  if [[ -f "defaults/kde/kservicemenurc" ]]; then
    install_file "defaults/kde/kservicemenurc" "${XDG_CONFIG_HOME}/kservicemenurc"
  elif [[ -f "dots/.config/kservicemenurc" ]]; then
    install_file "dots/.config/kservicemenurc" "${XDG_CONFIG_HOME}/kservicemenurc"
  fi

  # Dolphin panel layout state
  # Dolphin stores panel visibility in dolphinstaterc which overrides dolphinrc.
  # Policy:
  # - Fresh install: apply our clean layout so users don't get all panels enabled.
  # - Update: preserve user's custom layout by default.
  # - User can force reset via --reset-dolphin-layout.
  DOLPHIN_STATE_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/dolphinstaterc"
  if [[ "${INSTALL_FIRSTRUN}" == true || "${RESET_DOLPHIN_LAYOUT}" == true ]]; then
    if [[ -f "defaults/kde/dolphinstaterc" ]]; then
      mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}"
      install_file "defaults/kde/dolphinstaterc" "${DOLPHIN_STATE_FILE}"
      log_success "Dolphin panel layout state reset"
    elif [[ -f "${DOLPHIN_STATE_FILE}" ]]; then
      rm -f "${DOLPHIN_STATE_FILE}"
      log_success "Dolphin panel layout state cleaned"
    fi
  fi
fi

# Clean up obsolete .new files from previous installs
# These files are no longer created - kdeglobals and dolphinrc are always overwritten
for obsolete_new in "${XDG_CONFIG_HOME}/kdeglobals.new" \
                    "${XDG_CONFIG_HOME}/dolphinrc.new"; do
  if [[ -f "$obsolete_new" ]]; then
    rm -f "$obsolete_new"
    log_success "Cleaned obsolete ${obsolete_new##*/}"
  fi
done

# Kvantum (Qt theming)
if [[ -d "dots/.config/Kvantum" ]]; then
  install_dir "dots/.config/Kvantum" "${XDG_CONFIG_HOME}/Kvantum"
fi

# Copy Colloid theme to user Kvantum folder if installed
if [[ -d "/usr/share/Kvantum/Colloid" ]]; then
  tui_info "Setting up Kvantum Colloid theme..."
  mkdir -p "${XDG_CONFIG_HOME}/Kvantum/Colloid"
  cp -r /usr/share/Kvantum/Colloid/* "${XDG_CONFIG_HOME}/Kvantum/Colloid/"
  log_success "Kvantum Colloid theme configured"
fi

# Setup MaterialAdw folder for dynamic theming
mkdir -p "${XDG_CONFIG_HOME}/Kvantum/MaterialAdw"
if [[ -f "${XDG_CONFIG_HOME}/Kvantum/Colloid/ColloidDark.kvconfig" ]]; then
  cp "${XDG_CONFIG_HOME}/Kvantum/Colloid/ColloidDark.kvconfig" "${XDG_CONFIG_HOME}/Kvantum/MaterialAdw/MaterialAdw.kvconfig"
fi

# Vesktop themes (Discord theming with Material You colors)
if [[ -d "dots/.config/vesktop/themes" ]]; then
  mkdir -p "${XDG_CONFIG_HOME}/vesktop/themes"
  mkdir -p "${XDG_CONFIG_HOME}/Vesktop/themes"

  # Migrate: Remove old theme files from previous versions
  OLD_VESKTOP_THEMES=(
    "midnight-ii.theme.css"
    "dms-midnight.theme.css"
    "system24-ii.theme.css"
    "system24-palette.css"
    "ii-palette.css"
    "ii-system24.theme.css"
  )
  for old_theme in "${OLD_VESKTOP_THEMES[@]}"; do
    if [[ -f "${XDG_CONFIG_HOME}/vesktop/themes/${old_theme}" ]]; then
      rm -f "${XDG_CONFIG_HOME}/vesktop/themes/${old_theme}"
      log_success "Removed old Vesktop theme: ${old_theme}"
    fi
    if [[ -f "${XDG_CONFIG_HOME}/Vesktop/themes/${old_theme}" ]]; then
      rm -f "${XDG_CONFIG_HOME}/Vesktop/themes/${old_theme}"
      log_success "Removed old Vesktop theme: ${old_theme} (Vesktop/)"
    fi
  done

  install_dir "dots/.config/vesktop/themes" "${XDG_CONFIG_HOME}/vesktop/themes"
  install_dir "dots/.config/vesktop/themes" "${XDG_CONFIG_HOME}/Vesktop/themes"
  log_success "Vesktop Material You theme installed"

  # Best-effort verification (helps diagnose "update didn't apply" reports)
  VESKTOP_THEME_A="${XDG_CONFIG_HOME}/vesktop/themes/system24.theme.css"
  VESKTOP_THEME_B="${XDG_CONFIG_HOME}/Vesktop/themes/system24.theme.css"
  if [[ ! -f "$VESKTOP_THEME_A" && ! -f "$VESKTOP_THEME_B" ]]; then
    log_warning "Vesktop theme file was not found after install"
    log_warning "Expected: $VESKTOP_THEME_A"
    log_warning "      or: $VESKTOP_THEME_B"
    log_warning "Set SYSTEM24_PALETTE_CSS to your Vesktop themes path if it differs"
  fi
fi

# Fontconfig
if [[ -d "dots/.config/fontconfig" ]]; then
  install_dir__sync "dots/.config/fontconfig" "${XDG_CONFIG_HOME}/fontconfig"
fi

# Config (use defaults for distribution)
if [[ -f "defaults/config.json" ]]; then
  v mkdir -p "${DOTS_CORE_CONFDIR}"
  install_file__auto_backup "defaults/config.json" "${DOTS_CORE_CONFDIR}/config.json"
fi

# DISABLED: WebApp plugins — requires quickshell-webengine rebuild, re-enable when ready
# if [[ -d "defaults/plugins" ]]; then
#   PLUGINS_DIR="${XDG_CONFIG_HOME}/illogical-impulse/plugins"
#   v mkdir -p "$PLUGINS_DIR"
#   for plugin_dir in defaults/plugins/*/; do
#     plugin_name=$(basename "$plugin_dir")
#     dest="${PLUGINS_DIR}/${plugin_name}"
#     if [[ ! -d "$dest" ]]; then
#       log_info "Installing default plugin: $plugin_name"
#       v cp -r "$plugin_dir" "$dest"
#     else
#       # Update userscripts only (don't overwrite user's manifest/icon)
#       if [[ -d "${plugin_dir}scripts" ]]; then
#         v mkdir -p "${dest}/scripts"
#         v cp -r "${plugin_dir}scripts/"* "${dest}/scripts/" 2>/dev/null || true
#       fi
#     fi
#   done
# fi

#####################################################################################
# Apply required migrations automatically
#####################################################################################
if [[ "${SKIP_MIGRATIONS}" != "true" ]]; then
  run_migrations_auto
fi

repair_legacy_quickshell_malloc_environment || true

#####################################################################################
# Mark first run complete
#####################################################################################
function gen_firstrun(){
  x mkdir -p "$(dirname ${FIRSTRUN_FILE})"
  x touch "${FIRSTRUN_FILE}"
  x mkdir -p "$(dirname ${INSTALLED_LISTFILE})"
  realpath -se "${FIRSTRUN_FILE}" >> "${INSTALLED_LISTFILE}"
}

v gen_firstrun
v dedup_and_sort_listfile "${INSTALLED_LISTFILE}" "${INSTALLED_LISTFILE}"

#####################################################################################
# Environment variables are configured in Niri
#####################################################################################
tui_info "Configuring environment variables..."

# Primary: environment {} block in Niri config.kdl (already installed)
# Secondary: shell profile files for terminals outside Niri session (SSH, TTY, etc.)

# Verify Niri config has the variable
if grep -q "INIR_VENV" "${XDG_CONFIG_HOME}/niri/config.kdl" 2>/dev/null || \
   grep -q "ILLOGICAL_IMPULSE_VIRTUAL_ENV" "${XDG_CONFIG_HOME}/niri/config.kdl" 2>/dev/null; then
    log_success "Environment variable configured in Niri config"
else
    log_warning "INIR_VENV not found in Niri config"
fi

# Write shell profile env vars (for SSH, TTY, non-Niri terminals)
VENV_PATH="${XDG_STATE_HOME:-$HOME/.local/state}/quickshell/.venv"

# Bash: source from .bashrc
BASH_ENV_MARKER="# iNiR environment"
if [[ -f "$HOME/.bashrc" ]]; then
    # Clean up old markers
    sed -i '/iNiR-env.sh/d' "$HOME/.bashrc"
    # Remove any existing iNiR block
    sed -i "/${BASH_ENV_MARKER}/,/# end iNiR/d" "$HOME/.bashrc"
fi
cat >> "$HOME/.bashrc" << BEOF

${BASH_ENV_MARKER}
export INIR_VENV="${VENV_PATH}"
export ILLOGICAL_IMPULSE_VIRTUAL_ENV="\$INIR_VENV"
# Apply terminal color sequences (Material You from wallpaper)
if [ -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt ]; then
  cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
fi
# Starship prompt (fish is wired via config.fish; bash needs its own init)
if command -v starship >/dev/null 2>&1; then
  eval "\$(starship init bash)"
fi
# end iNiR
BEOF
log_success "Bash environment configured"

# Fish: conf.d snippet
FISH_CONF_DIR="${XDG_CONFIG_HOME}/fish/conf.d"
mkdir -p "$FISH_CONF_DIR"
cat > "${FISH_CONF_DIR}/inir-env.fish" << FEOF
# iNiR environment — auto-generated by setup install
set -gx INIR_VENV "${VENV_PATH}"
set -gx ILLOGICAL_IMPULSE_VIRTUAL_ENV "\$INIR_VENV"
FEOF
log_success "Fish environment configured"

# Zsh: source from .zshrc (if zsh is installed)
if [[ -f "$HOME/.zshrc" ]]; then
    sed -i '/iNiR-env.sh/d' "$HOME/.zshrc"
    sed -i "/${BASH_ENV_MARKER}/,/# end iNiR/d" "$HOME/.zshrc"
    cat >> "$HOME/.zshrc" << ZEOF

${BASH_ENV_MARKER}
export INIR_VENV="${VENV_PATH}"
export ILLOGICAL_IMPULSE_VIRTUAL_ENV="\$INIR_VENV"
# Apply terminal color sequences (Material You from wallpaper)
if [ -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt ]; then
  cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
fi
# Starship prompt (fish is wired via config.fish; zsh needs its own init)
if command -v starship >/dev/null 2>&1; then
  eval "\$(starship init zsh)"
fi
# end iNiR
ZEOF
    log_success "Zsh environment configured"
fi

# Fix Qt Icons (Apply GTK icon theme to KDE/Qt globals)
# This ensures Qt apps use the same icons as GTK apps
GTK_SETTINGS="${XDG_CONFIG_HOME}/gtk-3.0/settings.ini"
KDE_GLOBALS="${XDG_CONFIG_HOME}/kdeglobals"

if [[ -f "$GTK_SETTINGS" ]]; then
    ICON_THEME=$(grep "gtk-icon-theme-name" "$GTK_SETTINGS" | cut -d= -f2 | xargs)
    if [[ -n "$ICON_THEME" ]]; then
        if ! ${quiet:-false}; then
          tui_info "Applying icon theme '$ICON_THEME' to Qt/KDE..."
        fi

        # Ensure [Icons] section exists
        if ! grep -q "\[Icons\]" "$KDE_GLOBALS" 2>/dev/null; then
            mkdir -p "$(dirname "$KDE_GLOBALS")"
            echo -e "\n[Icons]" >> "$KDE_GLOBALS"
        fi

        # Update or add Theme key
        if grep -q "Theme=" "$KDE_GLOBALS"; then
            sed -i "s/^Theme=.*/Theme=$ICON_THEME/" "$KDE_GLOBALS"
        else
            # Insert after [Icons]
            sed -i "/\[Icons\]/a Theme=$ICON_THEME" "$KDE_GLOBALS"
        fi
        log_success "Qt icon theme configured"
    fi
fi

#####################################################################################
# Set default MIME associations (only if not already set)
#####################################################################################
tui_info "Configuring default applications..."

# Function to set MIME default only if not already configured or set to something broken
# Note: xdg-mime may fail without a graphical session, so we handle errors gracefully
set_mime_default_if_missing() {
    local mime_type="$1"
    local desktop_file="$2"

    # Check if the desktop file exists
    if [[ ! -f "/usr/share/applications/${desktop_file}" ]] && [[ ! -f "${XDG_DATA_HOME}/applications/${desktop_file}" ]]; then
        return 1  # Desktop file not available
    fi

    # xdg-mime requires a graphical session, skip if not available
    if ! command -v xdg-mime &>/dev/null; then
        return 1
    fi

    # Get current default (may fail without D-Bus session)
    local current_default
    current_default=$(xdg-mime query default "$mime_type" 2>/dev/null) || return 1

    # If no default set, or default is a non-editor for text files, set our default
    if [[ -z "$current_default" ]]; then
        xdg-mime default "$desktop_file" "$mime_type" 2>/dev/null || return 1
        return 0
    fi

    # For text files, check if current default is actually a text editor
    # (avoid cases where okular or other non-editors are set)
    if [[ "$mime_type" == text/* ]]; then
        case "$current_default" in
            *kate*|*gedit*|*code*|*vim*|*nvim*|*emacs*|*nano*|*sublime*|*atom*|*notepad*|*helix*|*zed*)
                # Already set to a proper editor, don't change
                return 1
                ;;
            *)
                # Not a known editor, set our default
                xdg-mime default "$desktop_file" "$mime_type" 2>/dev/null || return 1
                return 0
                ;;
        esac
    fi

    return 1  # Already has a valid default
}

# Detect available text editor (in order of preference)
TEXT_EDITOR=""
for editor in org.gnome.TextEditor.desktop org.gnome.gedit.desktop org.kde.kate.desktop code.desktop vim.desktop; do
    if [[ -f "/usr/share/applications/${editor}" ]] || [[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/applications/${editor}" ]]; then
        TEXT_EDITOR="$editor"
        break
    fi
done

# Set text editor defaults if we found one
if [[ -n "$TEXT_EDITOR" ]]; then
    set_mime_default_if_missing "text/plain" "$TEXT_EDITOR" && log_success "Set default text editor: $TEXT_EDITOR" || true
    # Also set for common config file types
    for mime in text/x-shellscript application/x-shellscript text/x-python text/x-script.python; do
        set_mime_default_if_missing "$mime" "$TEXT_EDITOR" 2>/dev/null || true
    done
fi

# Detect and set file manager (prefer Nautilus for GTK consistency with Niri)
FILE_MANAGER=""
for fm in org.gnome.Nautilus.desktop thunar.desktop pcmanfm.desktop org.kde.dolphin.desktop; do
    if [[ -f "/usr/share/applications/${fm}" ]] || [[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/applications/${fm}" ]]; then
        FILE_MANAGER="$fm"
        break
    fi
done

if [[ -n "$FILE_MANAGER" ]]; then
    set_mime_default_if_missing "inode/directory" "$FILE_MANAGER" && log_success "Set default file manager: $FILE_MANAGER" || true
fi

# Detect and set image viewer
IMAGE_VIEWER=""
for viewer in org.gnome.Loupe.desktop org.gnome.eog.desktop org.kde.gwenview.desktop feh.desktop; do
    if [[ -f "/usr/share/applications/${viewer}" ]] || [[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/applications/${viewer}" ]]; then
        IMAGE_VIEWER="$viewer"
        break
    fi
done

if [[ -n "$IMAGE_VIEWER" ]]; then
    for mime in image/png image/jpeg image/gif image/webp image/bmp; do
        set_mime_default_if_missing "$mime" "$IMAGE_VIEWER" 2>/dev/null || true
    done
    log_success "Set default image viewer: $IMAGE_VIEWER"
fi

# Detect and set PDF viewer
PDF_VIEWER=""
for viewer in org.gnome.Evince.desktop org.kde.okular.desktop zathura.desktop; do
    if [[ -f "/usr/share/applications/${viewer}" ]] || [[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/applications/${viewer}" ]]; then
        PDF_VIEWER="$viewer"
        break
    fi
done

if [[ -n "$PDF_VIEWER" ]]; then
    set_mime_default_if_missing "application/pdf" "$PDF_VIEWER" && log_success "Set default PDF viewer: $PDF_VIEWER" || true
fi

# Detect and set web browser
WEB_BROWSER=""
for browser in firefox.desktop chromium.desktop google-chrome.desktop brave-browser.desktop; do
    if [[ -f "/usr/share/applications/${browser}" ]] || [[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/applications/${browser}" ]]; then
        WEB_BROWSER="$browser"
        break
    fi
done

if [[ -n "$WEB_BROWSER" ]]; then
    for mime in x-scheme-handler/http x-scheme-handler/https text/html; do
        set_mime_default_if_missing "$mime" "$WEB_BROWSER" 2>/dev/null || true
    done
    log_success "Set default web browser: $WEB_BROWSER"
fi

tui_info "Copying wallpapers..."

#####################################################################################
# Copy bundled wallpapers to user's Pictures/Wallpapers (always, don't overwrite)
#####################################################################################
# Ensure II_TARGET is defined (in case SKIP_QUICKSHELL was set)
II_TARGET="${II_TARGET:-${XDG_CONFIG_HOME}/quickshell/inir}"
# Validate xdg-user-dir output: must be absolute and not equal to $HOME itself
_xdg_pictures="$(xdg-user-dir PICTURES 2>/dev/null || true)"
if [[ -z "$_xdg_pictures" || "$_xdg_pictures" != /* || "$_xdg_pictures" == "$HOME" ]]; then
  _xdg_pictures="$HOME/Pictures"
fi
USER_WALLPAPERS_DIR="${_xdg_pictures}/Wallpapers"
if [[ -d "${II_TARGET}/assets/wallpapers" ]]; then
  mkdir -p "${USER_WALLPAPERS_DIR}"
  COPIED_COUNT=0
  for wallpaper in "${II_TARGET}/assets/wallpapers"/*; do
    if [[ -f "$wallpaper" ]]; then
      dest="${USER_WALLPAPERS_DIR}/$(basename "$wallpaper")"
      if [[ ! -f "$dest" ]] || [[ ! -s "$dest" ]]; then
        cp -f "$wallpaper" "$dest"
        COPIED_COUNT=$((COPIED_COUNT + 1))
      fi
    fi
  done
  if [[ $COPIED_COUNT -gt 0 ]]; then
    log_success "Copied $COPIED_COUNT new wallpapers to ${USER_WALLPAPERS_DIR}"
  fi
fi

# Optional extra wallpapers (fresh install interactive only)
INIR_WALLS_DEFAULT_OVERRIDE=""
if [[ "${INSTALL_FIRSTRUN}" == true && "${ask}" == "true" ]]; then
  if tui_confirm "Download and install iNiR-Walls wallpapers?" "no"; then
    EXTRAS_INIR_WALLS_FIRST_IMAGE=""
    extras_install_inir_walls
    INIR_WALLS_FIRST="${EXTRAS_INIR_WALLS_FIRST_IMAGE}"
    if [[ -n "$INIR_WALLS_FIRST" ]] && tui_confirm "Replace iNiR default wallpaper selection with an iNiR-Walls wallpaper?" "yes"; then
      INIR_WALLS_DEFAULT_OVERRIDE="$INIR_WALLS_FIRST"
      log_success "Default wallpaper source switched to iNiR-Walls"
    fi
  fi
fi

# Optional monochrome icon theme (YAMIS by dirn-typo).
# Preinstalled on fresh installs, but non-intrusive: only places the theme files
# in user-scope. Does NOT change the user's icon theme — they switch via Settings.
if [[ "${INSTALL_FIRSTRUN}" == true ]]; then
  if [[ "${ask}" == "true" ]]; then
    if tui_confirm "Install YAMIS monochrome icon theme? (~23 MiB, GPL-3, optional)" "yes"; then
      extras_install_yamis_icons
    else
      log_info "Skipping YAMIS icons (can install later via './setup extras')"
    fi
  else
    extras_install_yamis_icons
  fi
fi

#####################################################################################
# Set default wallpaper and generate initial theme (first run only)
#####################################################################################
# Pick the first available wallpaper (don't hardcode a filename that may not exist)
DEFAULT_WALLPAPER=""
if [[ -n "$INIR_WALLS_DEFAULT_OVERRIDE" && -f "$INIR_WALLS_DEFAULT_OVERRIDE" && -s "$INIR_WALLS_DEFAULT_OVERRIDE" ]]; then
  DEFAULT_WALLPAPER="$INIR_WALLS_DEFAULT_OVERRIDE"
fi
for candidate in \
  "${USER_WALLPAPERS_DIR}/G5uBmitWkAAyk8s.jpg" \
  "${USER_WALLPAPERS_DIR}/Angel1.png" \
  "${USER_WALLPAPERS_DIR}/qs-niri.jpg"
do
  [[ -n "$DEFAULT_WALLPAPER" ]] && break
  if [[ -f "$candidate" && -s "$candidate" ]]; then
    DEFAULT_WALLPAPER="$candidate"
    break
  fi
done
# Fallback: pick any wallpaper in the directory
if [[ -z "$DEFAULT_WALLPAPER" ]]; then
  for f in "${USER_WALLPAPERS_DIR}"/*.{jpg,jpeg,png,webp}; do
    if [[ -f "$f" && -s "$f" ]]; then
      DEFAULT_WALLPAPER="$f"
      break
    fi
  done
fi
if [[ "${INSTALL_FIRSTRUN}" == true && -n "${DEFAULT_WALLPAPER}" && -f "${DEFAULT_WALLPAPER}" ]]; then
  tui_info "Setting default wallpaper..."

  # Ensure output directories exist for color generation
  mkdir -p "${XDG_STATE_HOME}/quickshell/user/generated"
  mkdir -p "${XDG_STATE_HOME}/quickshell/user/generated/wallpaper"
  mkdir -p "${XDG_CONFIG_HOME}/gtk-3.0"
  mkdir -p "${XDG_CONFIG_HOME}/gtk-4.0"
  mkdir -p "${XDG_CONFIG_HOME}/fuzzel"

  # Update config.json with default wallpaper path
  shell_config_json="${DOTS_CORE_CONFDIR}/config.json"
  if [[ -f "$shell_config_json" ]]; then
    if command -v jq >/dev/null 2>&1; then
      jq --arg path "${DEFAULT_WALLPAPER}" '.background.wallpaperPath = $path' \
        "$shell_config_json" > "${shell_config_json}.tmp" \
        && mv "${shell_config_json}.tmp" "$shell_config_json"
      log_success "Default wallpaper configured"
    fi
  fi

  # Generate initial theme colors using unified Python pipeline
  export INIR_VENV="${XDG_STATE_HOME}/quickshell/.venv"
  export ILLOGICAL_IMPULSE_VIRTUAL_ENV="${INIR_VENV}"
  _init_python_cmd="${INIR_VENV}/bin/python3"
  _init_gen_material="${II_TARGET}/scripts/colors/generate_colors_material.py"
  _init_template_dir="${XDG_CONFIG_HOME}/matugen"
  _init_scss_file="${XDG_STATE_HOME}/quickshell/user/generated/material_colors.scss"
  _init_json_file="${XDG_STATE_HOME}/quickshell/user/generated/colors.json"
  _init_palette_file="${XDG_STATE_HOME}/quickshell/user/generated/palette.json"
  _init_terminal_file="${XDG_STATE_HOME}/quickshell/user/generated/terminal.json"
  _init_meta_file="${XDG_STATE_HOME}/quickshell/user/generated/theme-meta.json"

  _init_py=""
  [[ -x "$_init_python_cmd" ]] && _init_py="$_init_python_cmd" || { command -v python3 &>/dev/null && _init_py="python3"; }

  if [[ -n "$_init_py" && -f "$_init_gen_material" ]]; then
    tui_info "Generating theme colors from wallpaper..."
    if "$_init_py" "$_init_gen_material" \
        --path "${DEFAULT_WALLPAPER}" --mode dark \
        --termscheme "${II_TARGET}/scripts/colors/terminal/scheme-base.json" --blend_bg_fg \
        --json-output "$_init_json_file" \
        --palette-output "$_init_palette_file" \
        --terminal-output "$_init_terminal_file" \
        --meta-output "$_init_meta_file" \
        --render-templates "$_init_template_dir" \
        > "$_init_scss_file" 2>/dev/null && [[ -s "$_init_json_file" ]]; then
      log_success "Theme colors generated"

      # Run applycolor.sh which handles GTK, KDE, Darkly, and terminal theming
      if [[ -s "$_init_scss_file" && -f "${II_TARGET}/scripts/colors/applycolor.sh" ]]; then
        bash "${II_TARGET}/scripts/colors/applycolor.sh" 2>/dev/null || true
        log_success "GTK/KDE/terminal theme colors applied"
      elif [[ -f "${II_TARGET}/scripts/colors/apply-gtk-theme.sh" ]]; then
        bash "${II_TARGET}/scripts/colors/apply-gtk-theme.sh" 2>/dev/null || true
        log_success "Qt Darkly theme colors generated (fallback)"
      fi
    else
      log_warning "Color generation failed. Theme may not work correctly."
    fi
  else
    log_warning "Python environment not available. GTK/Qt theming will not be applied."
  fi
fi

#####################################################################################
# Migrate: Generate Darkly.colors for existing users (Qt file dialogs fix)
#####################################################################################
DARKLY_COLORS_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/color-schemes/Darkly.colors"
if [[ ! -f "${DARKLY_COLORS_FILE}" ]]; then
  tui_info "Generating Darkly color scheme for Qt apps..."

  # Ensure directory exists
  mkdir -p "$(dirname "${DARKLY_COLORS_FILE}")"

  # Try to regenerate from existing material colors
  MATERIAL_COLORS="${XDG_STATE_HOME}/quickshell/user/generated/material_colors.scss"
  if [[ -f "${MATERIAL_COLORS}" && -f "${II_TARGET}/scripts/colors/apply-gtk-theme.sh" ]]; then
    # Run the apply script which will generate Darkly.colors
    bash "${II_TARGET}/scripts/colors/apply-gtk-theme.sh" 2>/dev/null || true
    if [[ -f "${DARKLY_COLORS_FILE}" ]]; then
      log_success "Darkly color scheme generated for Qt apps"
    fi
  fi
fi

#####################################################################################
# Reset first run marker
#####################################################################################
QUICKSHELL_FIRST_RUN_FILE="${XDG_STATE_HOME}/quickshell/user/first_run.txt"
if [[ "${INSTALL_FIRSTRUN}" == true ]]; then
  if [[ -f "${QUICKSHELL_FIRST_RUN_FILE}" ]]; then
    x rm -f "${QUICKSHELL_FIRST_RUN_FILE}"
  fi
fi

#####################################################################################
# Create version.json for ShellUpdates service
#####################################################################################
if [[ -n "${II_TARGET}" && -d "${II_TARGET}" ]]; then
  REPO_VERSION=""
  REPO_COMMIT=""
  if [[ -f "${REPO_ROOT}/VERSION" ]]; then
    REPO_VERSION=$(cat "${REPO_ROOT}/VERSION" | tr -d '[:space:]')
  fi
  if command -v git &>/dev/null && [[ -d "${REPO_ROOT}/.git" ]]; then
    REPO_COMMIT=$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo "")
  fi
  write_version_info_json "${II_TARGET}/version.json" "${REPO_VERSION:-0.0.0}" "${REPO_COMMIT:-unknown}" "setup-install"
  log_success "Version tracking configured"
fi

#####################################################################################
# Final status checks
#####################################################################################
WARNINGS=()

if ! command -v niri >/dev/null; then
  WARNINGS+=("Niri compositor not found in PATH")
fi

if [[ ! -f "${XDG_CONFIG_HOME}/niri/config.kdl" ]]; then
  WARNINGS+=("Niri config not found at ~/.config/niri/config.kdl")
fi

if ! command -v qs >/dev/null; then
  WARNINGS+=("Quickshell (qs) not found in PATH")
fi

#####################################################################################
# File verification
#####################################################################################
if ! ${quiet:-false}; then
  _FILES_ELAPSED=$(( SECONDS - _FILES_STAGE_START ))
  echo ""
  tui_section_start "File verification"
  echo -e "  ${STY_FAINT}Stage completed in ${_FILES_ELAPSED}s${STY_RST}"
  echo ""

  # Critical QML files
  _VERIFY_ERRORS=0
  for _crit_file in "shell.qml" "GlobalStates.qml" "modules/common/Config.qml" \
                    "modules/common/Appearance.qml" "services/NiriService.qml"; do
    if [[ -f "${II_TARGET:-${XDG_CONFIG_HOME}/quickshell/inir}/${_crit_file}" ]]; then
      tui_verify_ok "${_crit_file}"
    else
      tui_verify_fail "${_crit_file}" "MISSING"
      ((_VERIFY_ERRORS++))
    fi
  done

  # Config files
  echo ""
  for _cfg_path \
    in "${XDG_CONFIG_HOME}/niri/config.kdl:Niri config" \
       "${DOTS_CORE_CONFDIR}/config.json:iNiR config" \
       "${XDG_CONFIG_HOME}/matugen:Theming templates" \
       "${XDG_CONFIG_HOME}/fuzzel:Fuzzel config" \
       "${XDG_STATE_HOME}/quickshell/user/generated/colors.json:Theme colors"; do
    _cfg_file="${_cfg_path%%:*}"
    _cfg_label="${_cfg_path##*:}"
    if [[ -e "$_cfg_file" ]]; then
      tui_verify_ok "$_cfg_label"
    else
      tui_verify_skip "$_cfg_label" "not found (may be ok)"
    fi
  done

  echo ""
  if [[ $_VERIFY_ERRORS -gt 0 ]]; then
    tui_warn "$_VERIFY_ERRORS critical file(s) missing — run './setup doctor' to diagnose"
  else
    tui_success "All critical QML files verified"
  fi
  tui_section_end
fi

#####################################################################################
# Final Summary
#####################################################################################

# In quiet mode, just print a simple status line
if ${quiet:-false}; then
  if [[ "${IS_UPDATE}" == "true" ]]; then
    echo "iNiR: update complete"
  else
    echo "iNiR: install complete"
  fi
else
  echo ""
  echo ""

  if [[ "${IS_UPDATE}" == "true" ]]; then
    # Update-specific output
    printf "${STY_GREEN}${STY_BOLD}"
    cat << 'EOF'
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║                    ✓ Update Complete                         ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
EOF
    printf "${STY_RST}"
    echo ""

    echo -e "${STY_BLUE}${STY_BOLD}┌─ What was updated${STY_RST}"
    echo -e "${STY_BLUE}│${STY_RST}"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Quickshell inir synced to ~/.config/quickshell/inir/"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Missing keybinds added to Niri config (if any)"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Config migrations applied"
    echo -e "${STY_BLUE}│${STY_RST}"
    echo -e "${STY_BLUE}└──────────────────────────────${STY_RST}"
    echo ""
  else
    # Install output
    printf "${STY_GREEN}${STY_BOLD}"
    cat << 'EOF'
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║                  ✓ Installation Complete                     ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
EOF
    printf "${STY_RST}"
    echo ""

    echo -e "${STY_BLUE}${STY_BOLD}┌─ What was installed${STY_RST}"
    echo -e "${STY_BLUE}│${STY_RST}"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Quickshell inir copied to ~/.config/quickshell/inir/"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Niri config wired to the inir launcher"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} GTK/Qt theming (Material You + Kvantum + Darkly)"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Environment variables for ${DETECTED_SHELL:-your shell}"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} Default wallpaper and color scheme"
    echo -e "${STY_BLUE}│${STY_RST}  ${STY_GREEN}✓${STY_RST} User launcher, desktop entry, and icon"
    echo -e "${STY_BLUE}│${STY_RST}"
    echo -e "${STY_BLUE}└──────────────────────────────${STY_RST}"
    echo ""
  fi
fi

# Skip the rest of the summary in quiet mode
if ! ${quiet:-false}; then

  # Show warnings if any
  if [[ ${#WARNINGS[@]} -gt 0 ]]; then
    echo -e "${STY_YELLOW}${STY_BOLD}┌─ Warnings${STY_RST}"
    echo -e "${STY_YELLOW}│${STY_RST}"
    for warn in "${WARNINGS[@]}"; do
      echo -e "${STY_YELLOW}│${STY_RST}  ${STY_RED}⚠${STY_RST} ${warn}"
    done
    echo -e "${STY_YELLOW}│${STY_RST}"
    echo -e "${STY_YELLOW}└──────────────────────────────${STY_RST}"
    echo ""
  fi

  # REBOOT WARNING (first install only)
  if [[ "${IS_UPDATE}" != "true" ]]; then
    echo ""
    echo -e "${STY_CYAN}${STY_BOLD}┌─ Session Note${STY_RST}"
    echo -e "${STY_CYAN}│${STY_RST}"
    echo -e "${STY_CYAN}│${STY_RST}  ${STY_YELLOW}Log out or reboot${STY_RST} if new groups, env vars, or user services"
    echo -e "${STY_CYAN}│${STY_RST}  do not apply immediately in your current session."
    echo ""
  else
    echo -e "${STY_CYAN}${STY_BOLD}┌─ Session Note${STY_RST}"
    echo -e "${STY_CYAN}│${STY_RST}"
    echo -e "${STY_CYAN}│${STY_RST}  Reload Niri or restart the session if the updated launcher bindings"
    echo -e "${STY_CYAN}│${STY_RST}  are not visible immediately."
  fi
  echo -e "${STY_CYAN}└──────────────────────────────${STY_RST}"
  echo ""

  # Key shortcuts (only show on install, not update)
  if [[ "${IS_UPDATE}" != "true" ]]; then
    echo -e "${STY_PURPLE}${STY_BOLD}┌─ Key Shortcuts${STY_RST}"
    echo -e "${STY_PURPLE}│${STY_RST}"
    echo -e "${STY_PURPLE}│${STY_RST}  ${STY_INVERT} Super+Space ${STY_RST}     Search / Overview"
    echo -e "${STY_PURPLE}│${STY_RST}  ${STY_INVERT} Super+G ${STY_RST}         Overlay (widgets, tools)"
    echo -e "${STY_PURPLE}│${STY_RST}  ${STY_INVERT} Alt+Tab ${STY_RST}         Window switcher"
    echo -e "${STY_PURPLE}│${STY_RST}  ${STY_INVERT} Super+V ${STY_RST}         Clipboard history"
    echo -e "${STY_PURPLE}│${STY_RST}  ${STY_INVERT} Ctrl+Alt+T ${STY_RST}      Wallpaper picker"
    echo -e "${STY_PURPLE}│${STY_RST}  ${STY_INVERT} Super+/ ${STY_RST}         Show all shortcuts"
    echo -e "${STY_PURPLE}│${STY_RST}"
    echo -e "${STY_PURPLE}└──────────────────────────────${STY_RST}"
    echo ""
  fi

  echo -e "${STY_FAINT}Backups saved to: ${BACKUP_DIR}${STY_RST}"
  echo -e "${STY_FAINT}Logs: inir logs${STY_RST}"
  echo ""

  if [[ "${IS_UPDATE}" == "true" ]]; then
    echo -e "${STY_GREEN}Done. Hot reload should kick in any second now.${STY_RST}"
  else
    echo -e "${STY_GREEN}Install complete. iNiR is ready through the inir launcher.${STY_RST}"
  fi
  echo ""

fi  # end quiet check
