pragma Singleton

pragma ComponentBehavior: Bound

import QtCore
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import qs.modules.common
import qs.services

Singleton {
    id: root

    readonly property string socketPath: Quickshell.env("NIRI_SOCKET")

    property var workspaces: ({})
    property var allWorkspaces: []
    property int focusedWorkspaceIndex: 0
    property string focusedWorkspaceId: ""
    property var currentOutputWorkspaces: []
    property string currentOutput: ""
    readonly property bool actionReady: requestSocket.connected

    // Config load status (updated from ConfigLoaded event)
    property bool configLoaded: false
    property bool configLoadFailed: false
    property string configError: ""
    property var overviewHotCornersGlobal: ["topLeft"]
    property var overviewHotCornersByOutput: ({})
    property var overviewHotCornerOverrides: ({})
    property bool overviewHotCornersReady: false
    property string overviewHotCornersError: ""
    property bool _overviewHotCornersRefreshQueued: false

    signal configLoadFinished(bool ok, string error)

    property var outputs: ({})
    property var windows: []
    property var displayScales: ({})
    property var mruWindowIds: []
    property var activeWindow: null  // Currently focused window object

    readonly property int windowListUpdateIntervalMs: (GameMode.active
        ? (Config.options?.gameMode?.niriWindowListUpdateIntervalMsGameMode ?? 200)
        : (Config.options?.gameMode?.niriWindowListUpdateIntervalMs ?? 50))

    property bool inOverview: false
    readonly property bool singleWindowFullWidthEnabled: Config.options?.compositor?.autoExpandSingleTilingWindow ?? false

    property int currentKeyboardLayoutIndex: 0
    property var keyboardLayoutNames: []
    readonly property bool hasMultipleKeyboardLayouts: keyboardLayoutNames.length > 1
    // Tracks which workspaces have their single window auto-maximized
    property var _autoMaximizedWs: ({})

    signal windowUrgentChanged
    // Emitted only when membership or a spatial/matching key changes. Consumers
    // that order windows must not rebuild for title-only event-stream churn.
    signal windowOrderChanged
    // Note: activeWindowChanged signal is auto-generated by the activeWindow property

    onSingleWindowFullWidthEnabledChanged: {
        if (!singleWindowFullWidthEnabled) {
            _autoMaximizedWs = ({})
            return
        }
    }

    DankSocket {
        id: eventStreamSocket
        path: root.socketPath
        connected: CompositorService.isNiri

        onConnectionStateChanged: {
            if (connected) {
                send('"EventStream"')
                fetchOutputs()
                refreshOverviewHotCorners()
            }
        }

        parser: SplitParser {
            onRead: line => {
                try {
                    const event = JSON.parse(line)
                    handleNiriEvent(event)
                } catch (e) {
                    console.warn("NiriService: Failed to parse event:", line, e)
                }
            }
        }
    }

    DankSocket {
        id: requestSocket
        path: root.socketPath
        connected: CompositorService.isNiri
    }

    Process {
        id: fetchOutputsProcess
        command: ["niri", "msg", "-j", "outputs"]

        stdout: StdioCollector {
            id: fetchOutputsCollector
            onStreamFinished: {
                try {
                    const outputsData = JSON.parse(fetchOutputsCollector.text)
                    outputs = outputsData
                    console.info("NiriService: Loaded", Object.keys(outputsData).length, "outputs")
                    updateDisplayScales()
                    if (windows.length > 0) {
                        windows = sortWindowsByLayout(windows)
                    }
                    windowOrderChanged()
                } catch (e) {
                    console.warn("NiriService: Failed to parse outputs:", e)
                }
            }
        }
    }

    Process {
        id: overviewHotCornersProcess
        command: [
            "/usr/bin/python3",
            Quickshell.shellPath("scripts/niri-config.py"),
            "get-hot-corners"
        ]

        stdout: StdioCollector { id: overviewHotCornersCollector }

        onExited: exitCode => {
            if (exitCode === 0) {
                try {
                    const data = JSON.parse(overviewHotCornersCollector.text)
                    root.overviewHotCornersGlobal = Array.isArray(data.global)
                        ? data.global : ["topLeft"]
                    root.overviewHotCornerOverrides = data.overrides ?? ({})
                    root.overviewHotCornersByOutput = data.effective ?? ({})
                    root.overviewHotCornersReady = true
                    root.overviewHotCornersError = ""
                } catch (e) {
                    root.overviewHotCornersError = String(e)
                }
            } else {
                root.overviewHotCornersError = "get-hot-corners exited " + exitCode
            }

            if (root._overviewHotCornersRefreshQueued) {
                root._overviewHotCornersRefreshQueued = false
                overviewHotCornersProcess.running = true
            }
        }
    }


    // Debounce timer for fetchOutputs
    Timer {
        id: fetchOutputsDebounce
        interval: 200
        onTriggered: {
            if (CompositorService.isNiri)
                fetchOutputsProcess.running = true
        }
    }

    Timer {
        id: singleWindowCheckTimer
        interval: 150
        repeat: false
        property int targetWsId: -1
        onTriggered: root._applySingleWindowPolicy(targetWsId)
    }

    function fetchOutputs() {
        if (!CompositorService.isNiri)
            return
        fetchOutputsDebounce.restart()
    }

    function refreshOverviewHotCorners(): void {
        if (!CompositorService.isNiri)
            return
        if (overviewHotCornersProcess.running) {
            root._overviewHotCornersRefreshQueued = true
            return
        }
        overviewHotCornersProcess.running = true
    }

    function overviewHotCornersForOutput(outputName: string): var {
        const configured = root.overviewHotCornersByOutput?.[outputName]
        if (Array.isArray(configured))
            return configured
        const exactOverride = root.overviewHotCornerOverrides?.[outputName]
        if (Array.isArray(exactOverride))
            return exactOverride
        return Array.isArray(root.overviewHotCornersGlobal)
            ? root.overviewHotCornersGlobal : ["topLeft"]
    }

    function isOverviewHotCornerActive(outputName: string, cornerName: string): bool {
        return root.overviewHotCornersForOutput(outputName).includes(cornerName)
    }

    // Schedule a single-window check for a specific workspace after niri settles focus
    function _scheduleSingleWindowCheck(wsId): void {
        if (!CompositorService.isNiri || !root.singleWindowFullWidthEnabled)
            return
        if (GameMode.active || root.inOverview)
            return
        singleWindowCheckTimer.targetWsId = wsId
        singleWindowCheckTimer.restart()
    }

    // Core logic: count tiling windows on workspace, maximize or un-maximize accordingly
    function _applySingleWindowPolicy(wsId): void {
        if (!root.singleWindowFullWidthEnabled || wsId < 0)
            return
        if (GameMode.active || root.inOverview)
            return

        // Use the freshest window data available
        const winList = root._windowsDirty ? root._pendingWindows : root.windows
        const tilingWins = winList.filter(w => w.workspace_id === wsId && !w.is_floating)
        const isAutoMaxed = root._autoMaximizedWs[wsId] !== undefined

        if (tilingWins.length === 1) {
            const win = tilingWins[0]
            if (GameMode.isWindowFullscreen(win))
                return
            if (isAutoMaxed && root._autoMaximizedWs[wsId] === win.id)
                return

            // Window is already focused by niri (it's the only one), just maximize
            root.maximizeColumn()
            const next = Object.assign({}, root._autoMaximizedWs)
            next[wsId] = win.id
            root._autoMaximizedWs = next
        } else if (isAutoMaxed && tilingWins.length > 1) {
            // More than one window now -- un-maximize by focusing the tracked one and toggling
            const trackedId = root._autoMaximizedWs[wsId]
            root.focusWindow(trackedId)
            root.maximizeColumn()

            const next = Object.assign({}, root._autoMaximizedWs)
            delete next[wsId]
            root._autoMaximizedWs = next
        } else if (isAutoMaxed && tilingWins.length === 0) {
            // All windows gone, just clean up tracking
            const next = Object.assign({}, root._autoMaximizedWs)
            delete next[wsId]
            root._autoMaximizedWs = next
        }
    }

    function updateDisplayScales() {
        if (!outputs || Object.keys(outputs).length === 0)
            return

        const scales = {}
        for (const outputName in outputs) {
            const output = outputs[outputName]
            if (output.logical && output.logical.scale !== undefined) {
                scales[outputName] = output.logical.scale
            }
        }

        displayScales = scales
    }

    function sortWindowsByLayout(windowList) {
        const enriched = windowList.map(w => {
            const ws = workspaces[w.workspace_id]
            if (!ws) {
                return {
                    window: w,
                    outputX: 999999,
                    outputY: 999999,
                    wsIdx: 999999,
                    col: 999999,
                    row: 999999
                }
            }

            const outputInfo = outputs[ws.output]
            const outputX = (outputInfo && outputInfo.logical) ? outputInfo.logical.x : 999999
            const outputY = (outputInfo && outputInfo.logical) ? outputInfo.logical.y : 999999

            const pos = w.layout?.pos_in_scrolling_layout
            const col = (pos && pos.length >= 2) ? pos[0] : 999999
            const row = (pos && pos.length >= 2) ? pos[1] : 999999

            return {
                window: w,
                outputX: outputX,
                outputY: outputY,
                wsIdx: ws.idx,
                col: col,
                row: row
            }
        })

        enriched.sort((a, b) => {
            if (a.outputX !== b.outputX) return a.outputX - b.outputX
            if (a.outputY !== b.outputY) return a.outputY - b.outputY
            if (a.wsIdx !== b.wsIdx) return a.wsIdx - b.wsIdx
            if (a.col !== b.col) return a.col - b.col
            if (a.row !== b.row) return a.row - b.row
            return a.window.id - b.window.id
        })

        return enriched.map(e => e.window)
    }

    function handleNiriEvent(event) {
        const eventType = Object.keys(event)[0]

        // During GameMode, skip non-essential events to reduce CPU usage.
        // WindowsChanged and WindowLayoutsChanged MUST remain — they carry the
        // window size updates that GameMode needs to detect fullscreen exit.
        if (GameMode.active) {
            const criticalEvents = [
                'WindowFocusChanged',
                'WindowClosed',
                'WindowOpenedOrChanged',
                'WindowsChanged',
                'WindowLayoutsChanged',
                'WorkspaceActivated',
                'WorkspaceActiveWindowChanged',
                'WorkspacesChanged',
                'OutputsChanged',
                'ConfigLoaded',
                'KeyboardLayoutsChanged',
                'KeyboardLayoutSwitched',
            ]
            if (!criticalEvents.includes(eventType)) {
                return
            }
        }

        switch (eventType) {
        case 'WorkspacesChanged':
            handleWorkspacesChanged(event.WorkspacesChanged)
            break
        case 'WorkspaceActivated':
            handleWorkspaceActivated(event.WorkspaceActivated)
            break
        case 'WorkspaceActiveWindowChanged':
            handleWorkspaceActiveWindowChanged(event.WorkspaceActiveWindowChanged)
            break
        case 'WindowFocusChanged':
            handleWindowFocusChanged(event.WindowFocusChanged)
            break
        case 'WindowsChanged':
            handleWindowsChanged(event.WindowsChanged)
            break
        case 'WindowClosed':
            handleWindowClosed(event.WindowClosed)
            break
        case 'WindowOpenedOrChanged':
            handleWindowOpenedOrChanged(event.WindowOpenedOrChanged)
            break
        case 'WindowLayoutsChanged':
            handleWindowLayoutsChanged(event.WindowLayoutsChanged)
            break
        case 'OutputsChanged':
            handleOutputsChanged(event.OutputsChanged)
            break
        case 'OverviewOpenedOrClosed':
            handleOverviewChanged(event.OverviewOpenedOrClosed)
            break
        case 'ConfigLoaded':
            handleConfigLoaded(event.ConfigLoaded)
            break
        case 'KeyboardLayoutsChanged':
            handleKeyboardLayoutsChanged(event.KeyboardLayoutsChanged)
            break
        case 'KeyboardLayoutSwitched':
            handleKeyboardLayoutSwitched(event.KeyboardLayoutSwitched)
            break
        case 'WorkspaceUrgencyChanged':
            handleWorkspaceUrgencyChanged(event.WorkspaceUrgencyChanged)
            break
        }
    }

    function handleWorkspacesChanged(data) {
        const newWorkspaces = {}

        for (const ws of data.workspaces) {
            const oldWs = root.workspaces[ws.id]
            const updatedWs = {}
            for (const prop in ws)
                updatedWs[prop] = ws[prop]

            // Current Niri includes active_window_id in WorkspacesChanged and
            // that snapshot is authoritative. The original integration predates
            // that field and always copied the cached value over the fresh one;
            // once the cache held null, fullscreen/output ownership could stay
            // stale even while `niri msg workspaces` reported the real active
            // window. Preserve the cached value only for older event payloads
            // that genuinely omit the field.
            if (updatedWs.active_window_id === undefined
                    && oldWs && oldWs.active_window_id !== undefined)
                updatedWs.active_window_id = oldWs.active_window_id

            newWorkspaces[ws.id] = updatedWs
        }

        root.workspaces = newWorkspaces
        allWorkspaces = Object.values(newWorkspaces).sort((a, b) => a.idx - b.idx)

        focusedWorkspaceIndex = allWorkspaces.findIndex(w => w.is_focused)
        if (focusedWorkspaceIndex >= 0) {
            const focusedWs = allWorkspaces[focusedWorkspaceIndex]
            focusedWorkspaceId = focusedWs.id
            currentOutput = focusedWs.output || ""
        } else {
            focusedWorkspaceIndex = 0
            focusedWorkspaceId = ""
        }

        updateCurrentOutputWorkspaces()
        windowOrderChanged()
    }

    function handleWorkspaceActivated(data) {
        const ws = root.workspaces[data.id]
        if (!ws) {
            return
        }
        const output = ws.output

        const updatedWorkspaces = {}
        let hasChanges = false

        for (const id in root.workspaces) {
            const workspace = root.workspaces[id]
            const got_activated = workspace.id === data.id
            const needsUpdate = (workspace.output === output) || data.focused

            if (!needsUpdate) {
                updatedWorkspaces[id] = workspace
                continue
            }

            const updatedWs = {}
            for (let prop in workspace) {
                updatedWs[prop] = workspace[prop]
            }

            if (workspace.output === output) {
                updatedWs.is_active = got_activated
            }

            if (data.focused) {
                updatedWs.is_focused = got_activated
            }

            updatedWorkspaces[id] = updatedWs
            hasChanges = true
        }

        if (!hasChanges) return
        root.workspaces = updatedWorkspaces

        allWorkspaces = Object.values(updatedWorkspaces).sort((a, b) => a.idx - b.idx)

        focusedWorkspaceIndex = allWorkspaces.findIndex(w => w.is_focused)
        if (focusedWorkspaceIndex >= 0) {
            const focusedWs = allWorkspaces[focusedWorkspaceIndex]
            focusedWorkspaceId = focusedWs.id
            currentOutput = focusedWs.output || ""
        } else {
            focusedWorkspaceIndex = 0
            focusedWorkspaceId = ""
        }

        updateCurrentOutputWorkspaces()

        // When switching to a workspace, check single-window policy
        if (data.focused) {
            _scheduleSingleWindowCheck(data.id)
        }
    }

    function handleWindowFocusChanged(data) {
        const focusedWindowId = data.id
        root._latestFocusedWindowId = focusedWindowId

        if (focusedWindowId !== null && focusedWindowId !== undefined) {
            const newOrder = []
            for (let i = 0; i < mruWindowIds.length; i++) {
                const id = mruWindowIds[i]
                if (id !== focusedWindowId) {
                    newOrder.push(id)
                }
            }
            newOrder.unshift(focusedWindowId)
            mruWindowIds = newOrder
        }

        const currentList = root._windowsDirty ? root._pendingWindows : root.windows
        scheduleWindowsUpdate(currentList)
        const focusedWindow = currentList.find(window => window.id === focusedWindowId)

        if (focusedWindow) {
            const ws = root.workspaces[focusedWindow.workspace_id]
            if (ws && ws.active_window_id !== focusedWindowId) {
                const updatedWs = {}
                for (let prop in ws) {
                    updatedWs[prop] = ws[prop]
                }
                updatedWs.active_window_id = focusedWindowId

                const updatedWorkspaces = {}
                for (const id in root.workspaces) {
                    updatedWorkspaces[id] = id === focusedWindow.workspace_id ? updatedWs : root.workspaces[id]
                }
                root.workspaces = updatedWorkspaces
            }
        }
    }

    function handleWorkspaceActiveWindowChanged(data) {
        const ws = root.workspaces[data.workspace_id]
        if (!ws)
            return

        const updatedWs = {}
        for (let prop in ws)
            updatedWs[prop] = ws[prop]
        updatedWs.active_window_id = data.active_window_id

        const updatedWorkspaces = {}
        for (const id in root.workspaces)
            updatedWorkspaces[id] = id === data.workspace_id ? updatedWs : root.workspaces[id]
        root.workspaces = updatedWorkspaces
    }

    function handleWindowsChanged(data) {
        scheduleWindowsUpdate(data.windows)
    }

    function handleWindowClosed(data) {
        const currentList = _windowsDirty ? _pendingWindows : windows
        const closedWin = currentList.find(w => w.id === data.id)
        const closedWsId = closedWin?.workspace_id
        const updatedWindows = currentList.filter(w => w.id !== data.id)
        scheduleWindowsUpdate(updatedWindows)

        if (mruWindowIds && mruWindowIds.length > 0) {
            mruWindowIds = mruWindowIds.filter(id => id !== data.id)
        }

        // Check if the workspace now has a single tiling window
        if (closedWsId !== undefined) {
            _scheduleSingleWindowCheck(closedWsId)
        }
    }

    function handleWindowOpenedOrChanged(data) {
        if (!data.window)
            return

        const window = data.window
        const currentList = _windowsDirty ? _pendingWindows : windows
        const existingIndex = currentList.findIndex(w => w.id === window.id)
        let updatedWindows

        if (existingIndex >= 0) {
            updatedWindows = [...currentList]
            updatedWindows[existingIndex] = window
        } else {
            updatedWindows = [...currentList, window]
        }
        
        scheduleWindowsUpdate(updatedWindows)

        // New window opened -- check if workspace needs un-maximize or maximize
        if (existingIndex < 0 && window.workspace_id !== undefined) {
            _scheduleSingleWindowCheck(window.workspace_id)
        }
    }

    // Batching para actualizaciones de ventanas
    property bool _windowsDirty: false
    property var _pendingWindows: []
    property bool _windowOrderDirty: false
    property var _latestFocusedWindowId

    Timer {
        id: windowsUpdateTimer
        interval: root.windowListUpdateIntervalMs
        repeat: false
        onTriggered: {
            if (_windowsDirty) {
                const nextWindows = sortWindowsByLayout(_pendingWindows)
                const orderChanged = _windowOrderDirty
                windows = nextWindows
                activeWindow = nextWindows.find(window => window.is_focused) ?? null
                _windowsDirty = false
                _windowOrderDirty = false
                if (orderChanged)
                    windowOrderChanged()
            }
        }
    }

    function scheduleWindowsUpdate(newWindowsList) {
        const normalizedWindows = root._normalizeWindowFocus(newWindowsList)
        _windowOrderDirty = _windowOrderDirty
            || _windowOrderDiffers(_windowsDirty ? _pendingWindows : windows, normalizedWindows)
        _pendingWindows = normalizedWindows
        _windowsDirty = true
        if (!windowsUpdateTimer.running) {
            windowsUpdateTimer.restart()
        }
    }

    function _normalizeWindowFocus(windowList) {
        if (!Array.isArray(windowList) || root._latestFocusedWindowId === undefined)
            return windowList

        let changed = false
        const normalizedWindows = windowList.map(window => {
            const shouldBeFocused = root._latestFocusedWindowId !== null
                && window.id === root._latestFocusedWindowId
            if (window.is_focused === shouldBeFocused)
                return window

            changed = true
            const normalizedWindow = {}
            for (const prop in window)
                normalizedWindow[prop] = window[prop]
            normalizedWindow.is_focused = shouldBeFocused
            return normalizedWindow
        })
        return changed ? normalizedWindows : windowList
    }

    function _windowOrderDiffers(previousWindows, nextWindows) {
        if (!Array.isArray(previousWindows) || !Array.isArray(nextWindows))
            return true
        if (previousWindows.length !== nextWindows.length)
            return true

        const previousById = new Map()
        for (const window of previousWindows)
            previousById.set(window.id, window)

        for (const window of nextWindows) {
            const previous = previousById.get(window.id)
            if (!previous)
                return true
            if (previous.app_id !== window.app_id
                    || previous.workspace_id !== window.workspace_id
                    || !!previous.is_floating !== !!window.is_floating)
                return true

            const previousPos = previous.layout?.pos_in_scrolling_layout
            const nextPos = window.layout?.pos_in_scrolling_layout
            const previousColumn = Array.isArray(previousPos) ? previousPos[0] : undefined
            const previousRow = Array.isArray(previousPos) ? previousPos[1] : undefined
            const nextColumn = Array.isArray(nextPos) ? nextPos[0] : undefined
            const nextRow = Array.isArray(nextPos) ? nextPos[1] : undefined
            if (previousColumn !== nextColumn || previousRow !== nextRow)
                return true
        }

        return false
    }

    function handleWindowLayoutsChanged(data) {
        if (!data.changes)
            return

        // Usar _pendingWindows si hay cambios pendientes, o windows actual
        const currentList = _windowsDirty ? _pendingWindows : windows
        const updatedWindows = [...currentList]
        let hasChanges = false

        for (const change of data.changes) {
            const windowId = change[0]
            const layoutData = change[1]

            const windowIndex = updatedWindows.findIndex(w => w.id === windowId)
            if (windowIndex < 0)
                continue

            const updatedWindow = {}
            for (var prop in updatedWindows[windowIndex]) {
                updatedWindow[prop] = updatedWindows[windowIndex][prop]
            }
            updatedWindow.layout = layoutData
            updatedWindows[windowIndex] = updatedWindow
            hasChanges = true
        }

        if (!hasChanges)
            return

        scheduleWindowsUpdate(updatedWindows)
    }

    function handleOutputsChanged(data) {
        const nextOutputs = data?.outputs ?? {}
        outputs = nextOutputs
        updateDisplayScales()

        const outputNames = Object.keys(nextOutputs)
        let nextCurrentOutput = ""

        if (focusedWorkspaceIndex >= 0 && focusedWorkspaceIndex < allWorkspaces.length) {
            nextCurrentOutput = allWorkspaces[focusedWorkspaceIndex]?.output ?? ""
        }

        if ((!nextCurrentOutput || nextOutputs[nextCurrentOutput] === undefined) && outputNames.length > 0) {
            nextCurrentOutput = outputNames[0]
        }

        currentOutput = nextCurrentOutput
        updateCurrentOutputWorkspaces()

        // Force immediate update for outputs as it affects geometry calculations significantly
        windows = sortWindowsByLayout(windows)
        windowOrderChanged()
        fetchOutputs()
    }

    function handleOverviewChanged(data) {
        inOverview = data.is_open
    }

    function handleConfigLoaded(data) {
        const failed = data && data.failed
        configLoaded = !failed
        configLoadFailed = !!failed
        configError = (failed && data && data.error) ? data.error : ""

        if (!failed)
            refreshOverviewHotCorners()

        configLoadFinished(!failed, configError)
    }

    function applyKeyboardLayouts(data) {
        const layouts = data?.keyboard_layouts ?? data
        const names = Array.isArray(layouts?.names) ? layouts.names : []
        const index = Number(layouts?.current_idx ?? 0)

        keyboardLayoutNames = names
        currentKeyboardLayoutIndex = isNaN(index) ? 0 : index
    }

    function handleKeyboardLayoutsChanged(data) {
        applyKeyboardLayouts(data)
    }

    function handleKeyboardLayoutSwitched(data) {
        currentKeyboardLayoutIndex = data.idx
    }

    function handleWorkspaceUrgencyChanged(data) {
        const ws = root.workspaces[data.id]
        if (!ws)
            return

        const updatedWs = {}
        for (let prop in ws) {
            updatedWs[prop] = ws[prop]
        }
        updatedWs.is_urgent = data.urgent

        const updatedWorkspaces = {}
        for (const id in root.workspaces) {
            updatedWorkspaces[id] = id === data.id ? updatedWs : root.workspaces[id]
        }
        root.workspaces = updatedWorkspaces

        allWorkspaces = Object.values(updatedWorkspaces).sort((a, b) => a.idx - b.idx)

        windowUrgentChanged()
    }

    function updateCurrentOutputWorkspaces() {
        if (!currentOutput) {
            currentOutputWorkspaces = allWorkspaces
            return
        }

        const outputWs = allWorkspaces.filter(w => w.output === currentOutput)
        currentOutputWorkspaces = outputWs
    }

    function send(request) {
        if (!CompositorService.isNiri || !requestSocket.connected)
            return false
        requestSocket.send(request)
        return true
    }

    function toggleOverview() {
        return send({
                        "Action": {
                            "ToggleOverview": {}
                        }
                    })
    }

    function switchToWorkspace(workspaceIndex) {
        return send({
                        "Action": {
                            "FocusWorkspace": {
                                "reference": {
                                    "Index": workspaceIndex
                                }
                            }
                        }
                    })
    }

    // Focus a workspace by its stable id rather than by per-output index. An
    // Index reference resolves against the *focused* output, so it cannot
    // address a workspace on a different monitor; the id reference can. Used by
    // multi-monitor surfaces (e.g. the workspace strip) to switch to the exact
    // workspace under the pointer regardless of which output owns it.
    function switchToWorkspaceById(workspaceId) {
        return send({
                        "Action": {
                            "FocusWorkspace": {
                                "reference": {
                                    "Id": workspaceId
                                }
                            }
                        }
                    })
    }

    function focusWindow(windowId) {
        return send({
                        "Action": {
                            "FocusWindow": {
                                "id": windowId
                            }
                        }
                    })
    }

    function moveWindowToWorkspace(windowId, workspaceIndex, focus) {
        // Target the window directly by id so the move never has to focus it
        // first. Passing window_id avoids stealing the current view when
        // focus === false (e.g. reorganizing windows from the workspace strip).
        return send({
                        "Action": {
                            "MoveWindowToWorkspace": {
                                "window_id": windowId,
                                "reference": {
                                    "Index": workspaceIndex
                                },
                                "focus": focus === undefined ? false : focus
                            }
                        }
                    })
    }

    // Move a window onto a workspace addressed by its stable id. Like
    // switchToWorkspaceById, this is output-agnostic — an Index reference would
    // resolve against the focused output and could land the window on the wrong
    // monitor in a multi-output setup.
    function moveWindowToWorkspaceById(windowId, workspaceId, focus) {
        return send({
                        "Action": {
                            "MoveWindowToWorkspace": {
                                "window_id": windowId,
                                "reference": {
                                    "Id": workspaceId
                                },
                                "focus": focus === undefined ? false : focus
                            }
                        }
                    })
    }

    function closeWindow(windowId) {
        return send({
                        "Action": {
                            "CloseWindow": {
                                "id": windowId
                            }
                        }
                    })
    }

    function powerOffMonitors() {
        return send({
                        "Action": {
                            "PowerOffMonitors": {}
                        }
                    })
    }

    function powerOnMonitors() {
        return send({
                        "Action": {
                            "PowerOnMonitors": {}
                        }
                    })
    }

    function quit() {
        return send({
                        "Action": {
                            "Quit": {
                                "skip_confirmation": true
                            }
                        }
                    })
    }

    // ========== WORKSPACE NAVIGATION ==========
    function focusWorkspaceUp() {
        return send({ "Action": { "FocusWorkspaceUp": {} } })
    }
    function focusWorkspaceDown() {
        return send({ "Action": { "FocusWorkspaceDown": {} } })
    }

    // ========== COLUMN/WINDOW FOCUS ==========
    function focusColumnLeft() {
        return send({ "Action": { "FocusColumnLeft": {} } })
    }
    function focusColumnRight() {
        return send({ "Action": { "FocusColumnRight": {} } })
    }
    function focusColumnFirst() {
        return send({ "Action": { "FocusColumnFirst": {} } })
    }
    function focusColumnLast() {
        return send({ "Action": { "FocusColumnLast": {} } })
    }

    // ========== COLUMN MOVEMENT ==========
    function moveColumnToFirst() {
        return send({ "Action": { "MoveColumnToFirst": {} } })
    }
    function moveColumnToLast() {
        return send({ "Action": { "MoveColumnToLast": {} } })
    }

    // ========== COLUMN STATE ==========
    function maximizeColumn() {
        return send({ "Action": { "MaximizeColumn": {} } })
    }
    function consumeWindowIntoColumn() {
        return send({ "Action": { "ConsumeWindowIntoColumn": {} } })
    }
    function expelWindowFromColumn() {
        return send({ "Action": { "ExpelWindowFromColumn": {} } })
    }

    // ========== SIZING ==========
    function setColumnWidth(change) {
        return send({ "Action": { "SetColumnWidth": change } })
    }

    // ========== KEYBOARD ==========
    function switchLayout() {
        return send({ "Action": { "SwitchLayout": { "layout": "Next" } } })
    }
    function switchLayoutPrevious() {
        return send({ "Action": { "SwitchLayout": { "layout": "Prev" } } })
    }

    function getCurrentOutputWorkspaceNumbers() {
        // Niri workspaces already expose a 1-based idx for their position on the monitor.
        // Use idx directly as the workspace number for the current output.
        return currentOutputWorkspaces.map(w => w.idx)
    }

    function getCurrentWorkspaceNumber() {
        // Return the 1-based idx of the focused workspace on the current output.
        if (focusedWorkspaceIndex >= 0 && focusedWorkspaceIndex < allWorkspaces.length) {
            return allWorkspaces[focusedWorkspaceIndex].idx
        }
        // Fallback to the first workspace index if nothing is focused.
        return 1
    }

    function getCurrentKeyboardLayoutName() {
        if (currentKeyboardLayoutIndex >= 0 && currentKeyboardLayoutIndex < keyboardLayoutNames.length) {
            return keyboardLayoutNames[currentKeyboardLayoutIndex]
        }
        return ""
    }

    function findNiriWindow(toplevel) {
        if (!toplevel.appId)
            return null

        for (var j = 0; j < windows.length; j++) {
            const niriWindow = windows[j]
            if (niriWindow.app_id === toplevel.appId) {
                if (!niriWindow.title || niriWindow.title === toplevel.title) {
                    return {
                        "niriIndex": j,
                        "niriWindow": niriWindow
                    }
                }
            }
        }
        return null
    }

    // Map ToplevelManager's wayland-foreign-toplevel handles to Niri's authoritative
    // window list. Niri's `windows` is the source of truth: if a window isn't in
    // it, it doesn't exist, even if Wayland still has a stale handle for it (which
    // happens for apps that don't release the handle cleanly on close — zen,
    // electron, etc.). Returning the unmatched handles unenriched would surface
    // those ghosts in the dock/taskbar, which is exactly the persistence bug we
    // want to avoid.
    function sortToplevels(toplevels) {
        if (!toplevels || !CompositorService.isNiri)
            return toplevels ? [...toplevels] : []

        // Niri authoritative: 0 windows => 0 toplevels, regardless of stale handles.
        if (windows.length === 0)
            return []

        const usedToplevels = new Set()
        const enrichedToplevels = []

        for (const niriWindow of sortWindowsByLayout(windows)) {
            let bestMatch = null
            let bestScore = -1

            for (const toplevel of toplevels) {
                if (usedToplevels.has(toplevel))
                    continue

                const score = matchToplevelToWindow(toplevel, niriWindow)
                if (score > bestScore) {
                    bestScore = score
                    bestMatch = toplevel
                    if (score === 3)
                        break
                }
            }

            if (!bestMatch || bestScore <= 0)
                continue

            usedToplevels.add(bestMatch)
            enrichedToplevels.push(enrichToplevel(bestMatch, niriWindow))
        }

        // Intentionally DO NOT append unmatched toplevels: any toplevel without a
        // Niri window counterpart is a stale Wayland handle (ghost) and including
        // it would resurrect closed apps in the dock.
        return enrichedToplevels
    }

    function matchToplevelToWindow(toplevel, niriWindow) {
        if (toplevel.appId !== niriWindow.app_id)
            return 0

        let score = 1
        if (niriWindow.title && toplevel.title) {
            if (toplevel.title === niriWindow.title) {
                score = 3
            } else if (toplevel.title.includes(niriWindow.title) || niriWindow.title.includes(toplevel.title)) {
                score = 2
            }
        }
        return score
    }

    function enrichToplevel(toplevel, niriWindow) {
        const workspace = workspaces[niriWindow.workspace_id]
        const isFocused = niriWindow.is_focused ?? (workspace && workspace.active_window_id === niriWindow.id) ?? false
        const windowId = niriWindow.id

        const enriched = {
            "appId": toplevel.appId,
            "title": toplevel.title,
            "activated": isFocused,
            "niriWindowId": windowId,
            "niriWorkspaceId": niriWindow.workspace_id,
            "_sourceKey": `niri:${windowId}`,
            "_sourceToplevel": toplevel,
            "activate": function () {
                return NiriService.focusWindow(windowId)
            },
            "close": function () {
                if (toplevel.close) {
                    return toplevel.close()
                }
                return false
            }
        }

        for (let prop in toplevel) {
            if (!(prop in enriched)) {
                enriched[prop] = toplevel[prop]
            }
        }

        return enriched
    }

    function filterCurrentWorkspace(toplevels, screenName) {
        let currentWorkspaceId = null

        for (const workspace of allWorkspaces) {
            if (workspace.output === screenName && workspace.is_active) {
                currentWorkspaceId = workspace.id
                break
            }
        }

        if (currentWorkspaceId === null)
            return toplevels

        const workspaceWindows = windows.filter(window =>
            window.workspace_id === currentWorkspaceId)
        const usedToplevels = new Set()
        const result = []

        for (const niriWindow of workspaceWindows) {
            let bestMatch = null
            let bestScore = -1

            for (const toplevel of toplevels) {
                if (usedToplevels.has(toplevel))
                    continue

                const score = matchToplevelToWindow(toplevel, niriWindow)
                if (score > bestScore) {
                    bestScore = score
                    bestMatch = toplevel
                    if (score === 3)
                        break
                }
            }

            if (!bestMatch || bestScore <= 0)
                continue

            usedToplevels.add(bestMatch)
            result.push(enrichToplevel(bestMatch, niriWindow))
        }

        return result
    }

    // ========== TILING LAYOUTS ==========

    property string currentLayout: "off"
    readonly property var layouts: ["off", "master-left", "master-right", "columns", "monocle"]
    readonly property int tilingWindowCount: _currentWorkspaceWindows.length
    readonly property var _currentWorkspaceWindows: {
        const focusedWs = allWorkspaces.find(ws => ws.is_focused)
        if (!focusedWs) return []
        return windows.filter(w => w.workspace_id === focusedWs.id && !w.is_floating)
    }

    signal layoutChanged(string layout)
    signal layoutApplied(string layout, int windowCount)

    function cycleLayout(): void {
        const idx = layouts.indexOf(currentLayout)
        const nextIdx = (idx + 1) % layouts.length
        applyLayout(layouts[nextIdx])
    }

    function applyLayout(layoutName): void {
        if (!CompositorService.isNiri) return
        const wins = _currentWorkspaceWindows
        if (wins.length === 0) {
            currentLayout = layoutName
            layoutChanged(layoutName)
            return
        }

        // Reset: expel all windows to separate columns
        _resetLayout(wins.length)

        // Apply layout after reset
        _layoutTimer.layoutName = layoutName
        _layoutTimer.windowCount = wins.length
        _layoutTimer.start()
    }

    function _resetLayout(count): void {
        focusColumnFirst()
        for (let i = 0; i < count + 2; i++) {
            expelWindowFromColumn()
        }
    }

    Timer {
        id: _layoutTimer
        interval: 100
        property string layoutName: "off"
        property int windowCount: 0
        onTriggered: {
            switch (layoutName) {
                case "master-left": root._applyMasterLeft(windowCount); break
                case "master-right": root._applyMasterRight(windowCount); break
                case "columns": root._applyColumns(windowCount); break
                case "monocle": root._applyMonocle(windowCount); break
                default: break // "off" - already reset
            }
            root.currentLayout = layoutName
            root.layoutChanged(layoutName)
            root.layoutApplied(layoutName, windowCount)
        }
    }

    function _applyMasterLeft(count): void {
        if (count < 2) return
        // Master en col 0 (50%), stack en col 1
        focusColumnFirst()
        setColumnWidth("50%")
        focusColumnRight()
        // Consume todas las ventanas restantes hacia col 1
        for (let i = 0; i < count - 2; i++) {
            consumeWindowIntoColumn()
        }
    }

    function _applyMasterRight(count): void {
        if (count < 2) return
        // Stack en col 0, Master en col 1 (50%)
        // Primero: consumir todas excepto la última en col 0
        focusColumnFirst()
        for (let i = 0; i < count - 2; i++) {
            consumeWindowIntoColumn()
        }
        // Ahora tenemos 2 columnas: stack (col 0) y master (col 1)
        focusColumnRight()
        setColumnWidth("50%")
    }

    function _applyColumns(count): void {
        if (count < 1) return
        const width = Math.floor(100 / count) + "%"
        focusColumnFirst()
        for (let i = 0; i < count; i++) {
            setColumnWidth(width)
            focusColumnRight()
        }
    }

    function _applyMonocle(count): void {
        if (count < 1) return
        focusColumnFirst()
        setColumnWidth("100%")
        for (let i = 0; i < count - 1; i++) {
            consumeWindowIntoColumn()
        }
    }

    function promoteToMaster(): void {
        if (!CompositorService.isNiri) return
        if (currentLayout === "master-left") {
            moveColumnToFirst()
        } else if (currentLayout === "master-right") {
            moveColumnToLast()
        }
    }

    IpcHandler {
        target: "keyboard"

        function switchLayout(): void {
            NiriService.switchLayout()
        }

        function switchLayoutPrevious(): void {
            NiriService.switchLayoutPrevious()
        }

        function getCurrentLayout(): string {
            return NiriService.getCurrentKeyboardLayoutName()
        }

        function getLayouts(): string {
            return JSON.stringify(NiriService.keyboardLayoutNames)
        }
    }

}
